	const di18n = new DI18n({
	    locale: 'en',
	    isReplace: true,
	    messages:{
	       en: {
	          	navabout:'About',
	          	navservices:'Services',
	          	navcontact:'Contact',
	          	navhelp:'Help',
	          	navcareers:'Careers',
	          	login:'LOGIN',
	          	signup:'SIGN UP',
	          	en:'EN',
	          	ch:'CH',
	          	indextit:'V-STARS',
	          	indextit2:'Your Overseas Money Collection Partner',
	          	indextit3:'We make money collections from overseas marketplaces much easier,<br/> quicker and cheaper',
	          	indexdiscover:'DISCOVER',
	          	indexwhy:'WHY V-STARS',
	          	indexwhycon:'As an e-commerce seller, we know there are a lot of things you need to pay attention to and focus on – from procurement to logistics and from packaging to warehousing. Our team of payments experts want to reduce your burden by helping you to manage your funds flow in a more efficient way.',
	          	indexoffers:'V-STARS OFFERS',
	          	indexoffers1:'Local Bank Account',
	          	indexoffers2:'Competitive Exchange Rate',
	          	indexoffers3:'Fast Transfer',
	          	indexoffers4:'Fees Free',
	          	indexoffers5:'Easy Account Set Up',
	          	indexoffers6:'24/7 Online Access',
	          	indexofferscon1:'Collect money in USD, GBP and EUR from your marketplaces in US, UK and EU countries.',
	          	indexofferscon2:'Bring more of your money home by saving more on exchange rates.',
	          	indexofferscon3:'Make sure you get your money back as quick as possible.',
	          	indexofferscon4:'No registration fee, no accounts maintenance fee.',
	          	indexofferscon5:'Our CS team is always here to help and make your registration as simple and easy as possible.',
	          	indexofferscon6:'Book your deals anytime you want by logging into our online portal.',
	          	indexfees:'PRICING & FEES',
	          	indexfeestit1:'$0',
	          	indexfeestit2:'1%',
	          	indexfeesspan1:'         ',
	          	indexfeesspan2:'(or less)',
	          	indexfeesscon1:'No set up fee, no monthly fee, no additional fee on extra local accounts.',
	          	indexfeesscon2:'On top of the market exchange rate we get from our banking partners for every transfer you make. The more you transfer, the less we charge.',
				indexservices:'ADDITIONAL SERVICES',
				indexservicestit1:'VAT',
				indexservicestit2:'Supplier Payments',
				indexservicescon1:'Selling goods overseas especially in European Union (EU) usually incurs Value-Added Tax (VAT). V-Stars can help you pay VAT to tax authorities with your e-commerce proceeds.',
				indexservicescon2:'You may have suppliers in EU countries or United States that you have to settle payment with. V-Stars can help you manage the supplier payments in just a few clicks.',
				indexpates:'OUR RATES',
	          	indexpatescon:'We keep you informed with the latest rates movement so that you can stay ahead of the market.',
	          	indexpatestit1:'Live Rate & Graphs',
	          	indexpatestit2:'Free Rate Alerts',
	          	indexworks:'HOW IT WORKS',
	          	indexworkstit1:'Registration',
	          	indexworkstit2:'Link The Bank Account <br/>To Your Marketplace',
	          	indexworkstit3:'Make Transfers',
	          	indexworkscon1:'Click sign up and follow the steps for registration. Our CS team will be in touch with you shortly after registration.',
	          	indexworkscon2:'Input the bank details we provide to you to your marketplace and start receiving money.',
	          	indexworkscon3:'Book a deal through our online platform anytime you want and we will help you transfer the money back home.',
	          	footer1:'© 2023 by V-STARS CO., LIMITED',
	          	footer2:'Proudly created with zboory.com',
	          	
	          	aboutus:'ABOUT US',
	          	aboutuscon1:'V-Stars was founded by a team of payments experts who well understand how costly and time consuming it can be when it comes to overseas payments for sellers in China, especially SMEs, who are selling their goods overseas.',
	          	aboutuscon2:'We want to facilitate the funds flow for these sellers by making their overseas payments <i>quicker</i> , <i>cheaper</i> and <i>easier</i>.',
	          	abouthistory:'OUR HISTORY',
	          	abouthistorytit1:'Aug-Sep 2018',
	          	abouthistorytit2:'May 2018',
	          	abouthistorytit3:'JAN 2018',
	          	abouthistorytit4:'DEC 2017',
	          	abouthistorytit5:'NOV 2017',
	          	abouthistorytit6:'AUG 2017',
	          	abouthistorytit7:'AUG 2016',
	          	abouthistorycon1:'IT systems go-live & product launch',
	          	abouthistorycon2:'Opened a bank account as a segregated account for customers’ funds to do distribution',
	          	abouthistorycon3:'Obtained Money Service Operator License in Hong Kong',
	          	abouthistorycon4:'Moved to the office in Mira Place, Tsim Sha Tsui which can accommodate 30 people',
	          	abouthistorycon5:'Started the building of our in-house IT systems (backend an d frontend) with the help of an IT team in Beijing, China',
	          	abouthistorycon6:'Secured investor funding to kick start the operations date 30 people',
	          	abouthistorycon7:'Company Registration',
	          	aboutjoin:'JOIN US',
	          	aboutjoincon1:'It doesn’t matter whether you are a payments company or a trading company – staff matter. We believe that only when staff can enjoy their work, will they be able to deliver good results. By creating an open and friendly work environment, we hope our staff can communicate and share freely with their colleagues whenever they need and want to. ',
	          	aboutjoincon2:'<i>No hierarchy. No bureaucracy. No top-down management.</i>',
	        	aboutvalue:'OUR VALUES',
	        	aboutvaluetit1:'Collaboration',
	        	aboutvaluetit2:'Respect',
	        	aboutvaluetit3:'Support',
	        	aboutvaluetit4:'Curiosity',
	        	aboutvaluetit5:'Boldness',
	        	aboutvaluetit6:'Trust',
	        	aboutvaluecon1:'We believe in teamwork and collaboration. Synergy comes when talented people work together not alone.',
	        	aboutvaluecon2:'It doesn’t matter if you are a junior or senior staff. We respect good idea or suggestion from anyone. Raise it anytime.',
	        	aboutvaluecon3:'Support your co-worker whenever you can and get support from any co-worker whenever you need to. That’s how things work here.',
	        	aboutvaluecon4:'Most of the time, great idea comes from simple questions. Always be curious and keep asking questions.',
	        	aboutvaluecon5:'We encourage you to challenge assumptions or anything that does not make sense or sound correct to you. Take the initiative to make changes happen. Don’t be shy.',
	        	aboutvaluecon6:'We believe that our staff have the autonomy to get things done and deliver results. Micromanagement is not our style.',
	        	
	        	
	        	aboutbenefits:'OUR BENEFITS',
	        	aboutbenefitstit1:'Generous annual leave',
	        	aboutbenefitstit2:'Flexible working hours',
	        	aboutbenefitstit3:'Medical coverage',
	        	aboutbenefitstit4:'Subsidized team hangouts',
	        	aboutbenefitstit5:'Cozy and friendly work environment',
	        	aboutbenefitstit6:'Free breakfast',
	        	aboutpayment1:'PAYMENT MANAGER',
	        	aboutpayment2:'KYC SPECIALIST',
	        	services:'SERVICES',
	        	servicestit:'V-STARS Platform Payouts',
	        	servicescon1:'Collecting money from overseas marketplaces or buyers can be easy, quick, and cheap.',
	        	servicescon2:'V-Stars helps your business grow by facilitating your funds flow.',
	        	servicesvat:'VAT',
	       		servicesvatcon:'Sellers can use the balance in the EUR virtual bank account to pay VAT to tax authority in EU',
	        	servicesadvantagetit1:'SIMPLE',
	        	servicesadvantagetit2:'TRANSPARENT',
	        	servicesadvantagetit3:'COST-SAVING',
	        	servicesadvantagetit4:'TIME-SAVING',
	        	servicesadvantagecon1:'We believe a good product is always easy to use and understand. We apply the same philosophy to our payments solutions',
	        	servicesadvantagecon2:'We try to make our pricing transparent so that customers know exactly what they are paying for and what they are getting in return',
	        	servicesadvantagecon3:'We make our profit by helping our customers to save payments cost. We believe only when the business model is mutually beneficial will the company be to thrive in the long term.',
	        	servicesadvantagecon4:'"Time is money" is especially true for sellers who face a long  sales cycle. No matter it is about money collection or  pay-outs, we always aim to shorten the time it takes.',
	        	
	        	
	        	
	        	
	        	
	        	
	        	contacthear:'We’d love to hear from you!',
	        	contactcon:"We'd love to hear from you! Have questions or feedback? Simply use the form below to contact us, we'll get back to you as soon as possible.",
	        	contacthotline:'Our Address',
				contactemail:'Email',
				contactphone:'Tel',
				contacthotlinecon:'Units 1114-16,Mira Place TowerA , 132 Nathan Road,Tsim Sha Tsui, Hong Kong',
				contactemailcon:'enquiry@vstarsfx.com',
				contactphonecon:'852-3793-3400 (HK)',
				contactleavemessage:'Leave a Message',
				name:'Name*',
				tel:'Telephone*',
				subject:'Subject*',
				message:'Message*',
				send:'SEND',
				
	        	question:'FAQs',
	        	registration:'Registration',
	        	feesandcharges:'Fees and charges',
	        	accountoperations:'Account Operations',
	        	security:'Security',
	        	registrationtit1:'How long does it take to finish the whole registration?',
	        	registrationtit2:'When can I get details of my virtual bank account for money collection from marketplaces?',
	        	registrationtit3:'What documents do I need to provide to finish my registration?',
	        	registrationtit4:'Is there information that I need to provide during registration?',
	        	registrationtit5:'Is there any registration fee?',
	        	registrationtit6:'Which currency’s bank account does V-Stars provide?',
	        	registrationtit7:'What marketplaces can I use the virtual bank account to collect money from?',
	        	registrationtit8:'Can I receive money from eBay through my PayPal account?',
	        	registrationcon1:'We try to finish the account opening on the same day if you can provide all the information and documents required by our staff.',
	        	registrationcon2:'Once your registration is completed, our account manager will contact you right the way and send you the virtual bank account details.',
	        	registrationcon3:'If you register as a sole trader:',
	        	registrationcon4:'<span>•</span>Photo identify proof',
	        	registrationcon5:'<span>•</span>Proof of address issued within three months',
	        	registrationcon6:'If you register as a company:',
	        	registrationcon7:'<span>•</span>Certificate of Incorporation',
	        	registrationcon8:'<span>•</span>Latest information about company’s director & shareholder',
	        	registrationcon9:'<span>•</span>Director and shareholder’s photo identity proof and proof of address',
	        	registrationcon10:'Yes, you will need to provide information about your expected trading volume, types of goods sole and the marketplaces that you intend to collect money from. Our staff will guide you through the process, don’t worry.',
	        	registrationcon11:'No. Registration is free.',
	        	registrationcon12:'We provide EUR bank account and USD bank account only at the moment. EUR bank account can receive SEPA payments and USD bank account can receive ACH payments.',
	        	registrationcon13:'The virtual bank account can be used to collect money from most of the marketplaces, but you must send us the storefront link of the marketplace for checking before you start any money collection. If you are a B2B seller, please let us know before hand when your buyer is going to pay you money to the virtual bank account.',
	        	registrationcon14:'Yes, you can, but again, you have to provide the relevant storefront link(s) and PayPal transaction records for our checking before you do so.',
	        	feesandchargestit1:'How will V-Stars charge its customers?',
	        	feesandchargestit2:'If I receive USD in the virtual bank account, can I transfer USD back to my own account and do not do any currency conversion?',
	        	feesandchargestit3:'Can V-Stars charge me less than 0.7% fee?',
	        	feesandchargestit4:'Is V-Stars getting a competitive exchange rate?',
	        	feesandchargestit5:'What is the minimum amount I need to transfer?',
	        	feesandchargescon1:'We charge customers on transfer they make from the virtual bank account to their bank account. A maximum of 0.7% fee on the transaction amount will be charged. Other than that, we do NOT charge any fees.',
	        	feesandchargescon2:'You do not necessarily have to convert the currency you have received, but as mentioned above, a maximum of 0.7% fee on the transaction amount will be charged.',
	        	feesandchargescon3:'The more you transact with us, the lower we charge. Please contact your account manager when you have been trading with us for some time and want to see if you can get a lower fee.',
	        	feesandchargescon4:'Yes, we get the inter-bank exchange rate which individual customer can’t normally get from our partners.',
	        	feesandchargescon5:'You will have to transfer at least USD/EUR 500.',
	        	accountoperationstit1:'How do I make a transfer?',
	        	accountoperationstit2:'How do I enter my bank details for my own account?',
	        	accountoperationstit3:'How long do payments take to credit my bank account?',
	        	accountoperationscon1:'Before you make a transfer, you have to log in to your V-Stars account and add details of your own bank account. You can then transfer your balance anytime you like through the on-line system.',
	        	accountoperationscon2:'Log in to your V-Stars account and click on "create a new beneficiary". Input the details required which will then come through to us to verify. Please note that the beneficiary can either be your own account or in the name of tax authority if you are paying VAT.',
	        	accountoperationscon3:'Normally it will take 1-2 working days. In rare circumstances delays may occur. V-Stars will do everything reasonably possible to ensure that funds arrive on time but is not liable for delays caused by intermediary or receiving banks.',
	        	securitytit1:'How does V-Stars make sure my money is safe?',
	        	securitytit2:'Is my personal information well protected?',
	        	securitytit3:'What happen if I forgot my password?',
	        	securitycon1:'Ensuring the safety and security of your money is the most important part of our business. We ensure your funds are segregated from business funds.',
	        	securitycon2:'We are regulated in Hong Kong by the Hong Kong Customs and Excise, Money Services Supervision Bureau. We are required to hold sufficient capital to protect our business and safeguard our customers.',
	        	securitycon3:'V-Stars have the security system in place to protect customer information from unauthorised access. We will never share your personal information to any third parties other than those listed in the Terms & Conditions. Please read it carefully and let us know if you have any concerns.',
	        	securitycon4:'Click “Forgot Password” in the V-Stars log in page and follow the instructions to reset the password',
	        	
	        	paymentmanager:'PAYMENT MANAGER',
	        	paymentques1:'About V-Stars CO., Ltd',
	        	paymentans11:'We have just started our company to set foot in the B2C and B2B payments industry. We have received a new funding and would like to kick start our business.',
	        	paymentans12:'We are currently looking for a payments and operations manager to help us build and test our system and take care of the payments operations after system go-live. You will play a key role in the architecture of our payments system which is going to handle hundreds and even thousands of transactions a day.',
	        	paymentques2:'JOB REQUIREMENTS:',
	        	paymentans21:'Before system go-live:',
	        	paymentans22:'<span>•</span>Work together with IT team to design and test the payments system',
	        	paymentans23:'<span>•</span>Create and maintain a payments manual to record operation procedures and to ensure sufficient controls are in place',
	        	paymentans24:'After system go-live:',
	        	paymentans25:'<span>•</span>Ensure timely settlement of deals and execution of client payments and resolve any issues throughout the process',
	        	paymentans26:'<span>•</span>Cover open positions and check that deals are booked correctly',
	        	paymentans27:'<span>•</span>Work with other teams to make sure a smooth and accurate deal to payment process',
	        	paymentans28:'<span>•</span>Compile regular reporting such as volume, revenue and profit/loss calculation',
	        	paymentans29:'<span>•</span>Correspondence with counterparties relating to payments issues',
	        	paymentans210:'<span>•</span>Bank account reconciliation ',
	        	paymentans211:'<span>•</span>Payment investigations and trace enquiries ',
	        	paymentans212:'<span>•</span>Ensure that all settlement transactions are processed correctly and in a timely manner',
	        	paymentans213:'<span>•</span>Act as the point of contact for any payment issues',
	        	paymentans214:'<span>•</span>Expand and grow the payments team',
	        	paymentques3:'WHAT WE ARE LOOKING FOR:',
	        	paymentans31:'<span>•</span>At least 3 years’ working experience in payments operations',
	        	paymentans32:'<span>•</span>Sound working knowledge of payments system',
	        	paymentans33:'<span>•</span>Good numeric sense and detail-minded, good at dealing with numbers with accuracy',
	        	paymentans34:'<span>•</span>Proactively look for better solutions',
	        	paymentans35:'<span>•</span>Be open-minded and friendly (for you to communicate with other teams and lead your own team)',
	        	paymentans36:'<span>•</span>Speak business level Mandarin',
	        	paymentques4:'WHAT WE CAN OFFER:',
	        	paymentans41:'<span>•</span>A competitive salary, commensurate with experience',
	        	paymentans42:'<span>•</span>18 days’ annual leave',
	        	paymentans43:'<span>•</span>Discretionary bonus',
	        	paymentans44:'<span>•</span>MPF & health insurance coverage',
	        	paymentans45:'<span>•</span>Flexible working hours',
	        	paymentans46:'<span>•</span>Open and friendly work environment',
	        	paymentcontact:'Please email us your CV (in .doc or .pdf) to <span>careers@vstarsfx.com</span> if you are interested to apply for this position and would like to take a new challenge in your career life.',
	        	
	        	kycspecialist:'KYC SPECIALIST',
	        	kycques1:'V-Stars CO., Ltd',
	        	kycans11:'We have just started our company to set foot in the B2C and B2B payments industry. We have received a new funding and would like to kick start our business. If you are looking for a new challenge in your career and make a difference, please come and join the journey with us.',
	        	kycans12:'We are currently looking for a Know-Your-Customer (KYC) Specialist to help us onboard our customers in a smooth and efficient manner. You will be representing V-Stars to communicate with customers and collect identification documents to fulfil compliance requirements.',
	        	kycques2:'JOB REQUIREMENTS:',
	        	kycans21:'<span>•</span>Assist in the testing of KYC system',
	        	kycans22:'<span>•</span>Communicate with customers through emails and phone calls to collect identification documents and other related information',
	        	kycans23:'<span>•</span>Check and complete each customer’s KYC profile for compliance approval',
	        	kycans24:'<span>•</span>Respond to compliance team’s queries about customers’ profile',
	        	kycans25:'<span>•</span>Maintain customer on-boarding rate and customer satisfaction',
	        	kycans26:'<span>•</span>Report any suspicious scenarios',
	        	kycans27:'<span>•</span>Propose improvements to the KYC process',
	        	kycques3:'WHAT WE ARE LOOKING FOR:',
	        	kycans31:'<span>•</span>Speak fluent level Mandarin',
	        	kycans32:'<span>•</span>Business level English',
	        	kycans33:'<span>•</span>Be super friendly and super patient',
	        	kycans34:'<span>•</span>Attentive to details',
	        	kycans35:'<span>•</span>Basic understanding of KYC/AML requirements',
	        	kycans36:'<span>•</span>Good communication skill and be able to explain requirements in a simple way',
	        	kycques4:'WHAT WE CAN OFFER:',
	        	kycans41:'<span>•</span>A competitive salary, commensurate with experience',
	        	kycans42:'<span>•</span>18 days’ annual leave',
	        	kycans43:'<span>•</span>Discretionary bonus',
	        	kycans44:'<span>•</span>MPF / Health insurance coverage',
	        	kycans45:'<span>•</span>Flexible working hours',
	        	kycans46:'<span>•</span>Open and friendly work environment',
	        	
	        	conditionstit:'V-Stars Terms and Conditions (v1.0)',
	        	conditionstit1:'1. About V-Stars',
	        	conditionstit2:'2. Scope',
	        	conditionstit3:'3. Registration',
	        	conditionstit4:'4. Services',
	        	conditionstit5:'5. Incoming Funds',
	        	conditionstit6:'6. Settlement',
	        	conditionstit7:'7. Maintenance and Security',
	        	conditionstit8:'8. Prohibited Transactions',
	        	conditionstit9:'9. General Representation & Warranties',
	        	conditionstit10:'10. Contract Termination & Complaints',
	        	conditionstit11:'11. Liability, Indemnification and Disclaimers',
	        	conditionstit12:'12. Miscellaneous ',
	        	conditionstit13:'13. Definitions ',
	        	conditionscon11:'V-Stars Co., Limited (“V-Stars”, “we”, “us”, “our company”) is a company registered in Hong Kong as a Limited Liability Company. We are also registered as a Money Service Operator with the Hong Kong Customs and Excise. Our official website is: <i>www.vstarsfx.com.</i> ',
	        	conditionscon21:'2.1 The Terms and Conditions (“T&Cs”) set out here apply when you register with V-Stars and use our payments services.  Please read them carefully and make sure you have understood the content. You will be asked to accept and agree to the terms and conditions upon registration. Please contact us for clarifications should you have any questions about the T&Cs.',
	        	conditionscon22:'2.2 V-Stars may amend the T&Cs regularly due to regulatory changes or for other business reasons. We shall notify you by email if there are any changes in the T&Cs and you can always check the latest version of the T&Cs in our official website. The changes will come into effect immediately unless otherwise specify. Your continued use of our services after any changes to the T&Cs constitute your consent to such changes.',
	        	conditionscon23:'2.3 The T&Cs shall be governed by and construed in accordance with the laws of Hong Kong. All parties agree to irrevocably submit to the exclusive jurisdiction of the courts of Hong Kong.',
	        	conditionscon24:'2.4 We may translate these T&Cs to other languages from time to time for reference and information purpose. In the event of any inconsistency or conflict between the English version and version(s) in other language(s), the English version shall always prevail.',
	        	conditionscon31:'3.1 A corporate or an individual can register to use the V-Stars Services in our official website. Before accessing or using any V-Stars Services, we shall require a V-Star Account to be opened, and for such purposes, customers are required to provide information and documents requested by V-Stars from time to time. During and upon opening of the V-Stars Account, we shall have the right to request any additional information and document from you, including, but not limited to, information on your directors and shareholders, and your nature of business, corporate and financial information. ',
	        	conditionscon32:'3.2 Upon providing such information, you shall keep us informed of any changes promptly by e-mail or through our designated system or channel from time to time. By requesting the opening of a V-Stars Account, you shall be deemed to give consent to V-Stars for verification of your registration information against third party databases.',
	        	conditionscon33:"3.3 If you register the V-Stars Services on behalf of a corporate, you must be legally authorized under the business entity's formation documents and/or otherwise under applicable law.",
	        	conditionscon34:'3.4 V-Stars reserves all the rights to open or reject the V-Stars Account to any corporate or individual. V-Stars also reserves the rights to terminate any V-Stars Account at any time. In case of an unsuccessful application or termination, V-Stars is not obliged to provide any reason.',
	        	conditionscon35:'3.5 If your V-Stars Account is opened successfully, V-Stars will notify you via email and we will provide you with your V-Stars log in credentials in such email. Your log in credentials are unique to you and it is your responsibility to keep this information safe. You must always take all reasonable steps to keep your V-Stars Account user name and password safe and strictly confidential and you shall never disclose it to anyone. You should notify us immediately if you have noticed any unauthorized use or access to your V-Stars Account. By accessing the V-Stars Account through a correct user name and password, it shall be deemed that such account has been accessed legally and under your authorization, and you agree that you will be liable for the Transactions and Fees incurred by such use.',
	        	conditionscon41:'4.1 The V-Stars Services consist of you, receiving funds in a V-Stars Bank Account from Marketplaces through V-Stars as your agent. V-Stars is an independent contractor that acts solely as an agent for you, the payee in respect of the Funds. V-Stars does not act as a fiduciary, trustee or escrow holder on your behalf. ',
	        	conditionscon42:'4.2 V-Stars assumes no liability to or in respect of any Buyer or Marketplace or otherwise in respect of any Product or any other part of your business. You assume exclusive responsibility for your Product, Buyers and Marketplaces and shall indemnify and hold V-Stars, its directors, officers, employees and agents harmless from any claim by any of them against V-Stars. ',
	        	conditionscon43:'4.3 The V-Stars Account and the related V-Stars Services are only intended for use to receive the Inbound Payments from Marketplaces and remit the same to the Customer Bank Account. You shall not allow the Marketplaces any right to debit the V-Stars Bank Account and you shall be liable to V-Stars for any debits made on such account by Marketplaces or any other third parties.',
	        	conditionscon44:'4.4 V-Stars shall use reasonable effort to inform you of any Inbound Payments of Funds into the V-Stars Bank Account through your V-Stars Account. V-Stars offers no guarantee that such information will be accurate, complete or timely.',
	        	conditionscon45:'4.5 V-Stars reserves the right to offset from any settlement to you any funds owed to V-Stars by you, including, but not limited to, all Fees payable under this T&Cs or otherwise.',
	        	conditionscon46:'4.6 You may be required to provide V-Stars with additional information and documents prior to using V-Stars Services. Such additional information might include documents allowing V-Stars to verify the identity of your entity’s shareholders. Additional information includes, but is not limited to supporting transaction data, and payment confirmation from the Marketplaces. Failure to provide such requested information may result in us denying your use of V-Stars Services.',
	        	conditionscon47:'4.7 Funds may be temporarily withheld if V-Stars or one of its Service Providers determines that the proposed transaction, transfer, remittance or settlement may violate any applicable laws or regulations. Funds may be forfeited as per the requirements of applicable laws or regulations.',
	        	conditionscon48:'4.8 The V-Stars Bank Account allocated under our Services is not a typical bank account nor do they offer the features and benefits of a bank account. Customers are not entitled to any interest for deposits in the V-Stars Bank Account. ',
	        	conditionscon49:'4.9 Funds are your property. No person or entity other than such registered user has any rights in relation to Funds. You may not assign or transfer your right to utilize the V-Stars Services to a third party or otherwise grant any third party a legal or equitable interest in connection with your use of the V-Stars Services.',
	        	conditionscon410:'4.10 The use of our Services requires prior registration with V-Stars. And You agree to provide us with complete and accurate information upon registration. The V-Stars Services are intended to enable payments for e-commerce-related activities and are not intended for personal or illegal use.',
	        	conditionscon411:'4.11 You are fully responsible for all applicable government taxes in connection with or related to the V-Stars Services, including but not limited to the tax incurred from the sell and purchase of the Products, the Funds received and all related tax reporting obligations.',
	        	conditionscon412:'4.12 If your V-Stars Account has remained inactive or idle without any Transactions for over six (6) years, the remaining Funds in the V-Stars Account shall be deemed to be renounced by you, and we may forfeit such Funds.',
	        	conditionscon413:'4.13 We reserve the right to terminate your V-Stars Service at any time and you may cancel your V-Stars Service at any time. It is strictly forbidden to use the V-Stars Service for any illegal purposes including, but not limited to, fraud and money laundering. You are prohibited from using the V-Stars Service in any attempt to abuse, exploit, or circumvent any law or regulation.',
	        	conditionscon51:'5.1 Our V-Stars Bank Account enables you to receive Funds from Marketplaces. V-Stars Bank Account is currently available in USD and EUR, and we may enable additional currencies from time to time. You shall make sure that settlement of Funds through the V-Stars Bank Account does not breach your agreement with Marketplaces. Only Marketplaces approved by V-Stars can make payments to your V-Stars Bank Account. Approval of Marketplaces are at the sole and absolute discretion of V-Stars. You shall declare the Marketplaces where you are going to receive from before using V-Stars Bank Account for this purpose. Any Inbound Payments sent by Marketplaces that are not approved by V-Stars may be rejected. Any costs and expenses associated with rejected payments shall be borne by you.',
	        	conditionscon52:'5.2 Upon registration with V-Stars, you will be provided with the banking information you may need to receive funds from Marketplaces. You shall provide the information to the Marketplaces from whom you wish to receive payment from.',
	        	conditionscon53:'5.3 V-Stars Bank Account is not a bank account and you shall not attempt to use the V-Stars Bank Account as a bank account. You agree to avoid any direct communication with any banks or service providers that are involved in supporting the V-Stars Service. Any direct contact with a bank or other provider regarding the V-Stars Service may result in immediate termination of your use of the V-Stars Service.',
	        	conditionscon54:'5.4 V-Stars USD Bank Account will only accept funds received via ACH credit transfers from approved Marketplaces. V-Stars EUR Bank Account will only accept funds received via SEPA credit transfers from approved Marketplaces in the European Economic Area. Other Inbound Payments in other currencies may be enabled from time to time by V-Stars. ',
	        	conditionscon55:'5.5 V-Stars does not support any cash, credit card payments, wire transfers or checks for Inbound Payments. We reserve the right to reject and return partial or full Inbound Payments at any time. Payments may be rejected for any reason, including but not limited to reasons related to compliance with the Bank Secrecy Act / Anti-money Laundering / Office of Foreign Asset Control regulation or V-Stars compliance policies. When rejecting or returning a payment, we will be under no obligation to disclose the details for the rejection.',
	        	conditionscon56:'5.6 The time it takes for Inbound Payments to reach V-Stars is not in our control. If an Inbound Payment is not received within five (5) Business Days, we will initiate an internal investigation on your behalf given that you have made such requests to us. Any issues or disputes associated with Marketplaces and their policies should be resolved directly by you with the Marketplaces and are not the responsibility of V-Stars.',
	        	conditionscon57:'5.7 V-Stars discloses its fees and charges on our official website or you can check specifically upon log in to your V-Stars Account. Depending on the transaction volume, V-Stars adopts a tiered-level fees structure. V-Stars may also offer promotions in the form or refunds, reduced fees, and bonuses. The fees charged for V-Stars Services may be modified from time to time at V-Stars sole and absolute discretion. If you have any questions or are unclear as to any fees, you should contact V-Stars customer service.',
	        	conditionscon58:'5.8 Inbound Payments sent by payers that are not approved by V-Stars will be declined and returned. Any costs and expenses associated with declined payments shall be borne by you or the payers, whichever applicable. If a payment is rejected for any reason, fees may be charged by the bank or other providers sending the payment. You are solely responsible for any fees incurred in connection with payments that are rejected.',
	        	conditionscon61:'6.1 In order to complete settlement of your Funds to your Customer Bank Account, you must logon to your V-Stars Account and request a fund settlement. You need to provide the bank account details of your Customer Bank Account. You must not request settlement to any Customer Bank Account that is not in the same name of your V-Stars Account unless if you are paying tax to government authority.',
	        	conditionscon62:'6.2 You must ensure that your Customer Bank Account information is correct and accurate. We cannot be held responsible for Funds being sent to a wrong bank account because of you providing incorrect payment details. If a payment is rejected for such reason, the banking charge incurred may be deducted from your customer balance. In case of any incorrect or misdirected payment, we shall take reasonable measures to assist you with tracing and, if reasonably possible, recovering such payments, but we shall not be liable for any payments that cannot be recovered.',
	        	conditionscon63:'6.3 V-Stars may rely on third party banking counterparts or on local payment providers with whom we have payment arrangements and who are regulated in China and comply with the local laws to complete settlement.',
	        	conditionscon64:'6.4. V-Stars will initiate a settlement to your Customer Bank Account in the amount you settle, less any applicable Fees. Any Fees charged by your Customer Bank Account are not the responsibility of V-Stars. ',
	        	conditionscon65:'6.5 If requested by Marketplace, or if V-Stars deems it necessary in its sole discretion, V-Stars can provide a receipt in the name of Merchant evidencing Transaction Funds via V-Stars. Merchant authorizes V-Stars to provide a copy of this agreement as well as Transaction information to any Marketplace that requests information concerning the Merchant or settlements to the V-Stars Bank Account.',
	        	conditionscon71:'7.1 You must ensure that your information on record with V-Stars is always accurate and up to date and we shall not be liable for any loss arising from your failure to do so. We may, at any time, ask you to confirm the accuracy of your information or to provide documents or other evidence to verify such information.',
	        	conditionscon72:'7.2 We may contact you by email, by phone or in other ways, with information or notices regarding your use of the V-Stars Services. It is your responsibility to regularly check your V-Stars account and the proper functioning of your email account or other methods of communication that you have provided to V-Stars and to promptly retrieve and read messages sent by V-Stars or its staff. You will be solely liable for any loss that directly results from your failure to submit or notify us of a change in your contact details.',
	        	conditionscon73:'7.3 Information regarding payments received, withdrawals and other V-Stars Services activities are available in your V-Stars account which you can log in through our official website. You can find details of every transaction in the Transaction History.',
	        	conditionscon74:'7.4 Monthly statement will be prepared by us within 10 Business Days after the end of each month. Such monthly statement may be sent directly to your email or be available at our website after log in. You are strongly encouraged to check the statement regularly. All the details shown in the monthly statement shall be deemed correct and conclusive if no written notice of objection is received by us 30 days after the date of such statement.',
	        	conditionscon75:'7.5 If your V-Stars Account has had no activity in the past six months, we may consider you to be inactive. Once you are deemed inactive, we will disable certain features and services in your V-Stars Account or may even suspend your use of the V-Stars Service. You may request V-Stars to reactive your status if you are deemed inactive. V-Stars may reactive your status, in its sole discretion. You may also be required to send us new documents for re-verification purpose.',
	        	conditionscon76:'7.6 You must also take all reasonable steps to keep your security procedures secret and safe, and you must take all reasonable steps to prevent loss, theft or fraudulent misuse of them. We will make reasonable effort to protect your personal information from accidental loss and from unauthorized access, use or disclosure. However, we cannot guarantee that unauthorized third parties will never be able to get access to such personal information for improper purposes. You acknowledge that there is such a risk and is willing to bear it at your own cost. If you know or suspect that your security procedures have been lost, stolen or misappropriated, or that there have been unauthorised transactions or payments or other security breach, you must notify us immediately.',
	        	
	        	conditionscon771:'7.7 The personal data we collect may be used for the following purposes:',
	        	conditionscon772:'<span>a)</span> The daily operation of the Payment Services, wire transfers and related services under this Terms and Conditions provided to Customers; ',
	        	conditionscon773:'<span>b)</span> Conducting verification checks;',
	        	conditionscon774:'<span>c)</span> Assisting other financial institutions, including banks and service providers, to conduct thier checks; ',
	        	conditionscon775:'<span>d)</span> Designing financial services or related products for Customers’ use;',
	        	conditionscon776:'<span>e)</span> Marketing V-Stars services and products;',
	        	conditionscon777:'<span>f)</span> Meeting the requirements to make disclosure under the requirements of any law binding on V-Stars.',
	        	conditionscon781:'7.8 Personal data held by V-Stars will be kept confidential, but we may provide such information to the following parties (whether within or outside Hong Kong) for the purposes set out above: ',
	        	conditionscon782:'<span>a)</span> Any third-party service providers who provide administrative, telecommunications, computer, payment clearing or other services to V-Stars in connection with the operation of its business;',
	        	conditionscon783:'<span>b)</span> Any other person under a duty of confidentiality to V-Stars who has undertaken to keep such information confidential;',
	        	conditionscon784:'<span>c)</span> Banking counterparties and beneficiary banks or service providers providing necessary account information in respect of services to be provided under this Terms & Conditions; ',
	        	conditionscon785:'<span>d)</span> Your Authorised User(s) or other persons acting on your behalf in connection with provision of the services under this Terms & Conditions; ',
	        	conditionscon786:'<span>e)</span> Any person to whom V-Stars is under an obligation to make disclosure under the requirements of any law binding on us or under and for the purposes of any guidelines issued by regulatory or other authorities with which they are expected to comply;',
	        	
	        	conditionscon79:'7.9 We do not sell any personal data that we hold about you. If you do not wish us to use your personal data for direct marketing purpose, please indicate your objection during registration by not ticking the relevant box as it represents your present choice about whether to receive direct marketing contact or information. ',
	        	conditionscon710:'7.10 We will only retain your personal data for as long as is necessary but generally no more than six years after the end of our business relationship with you. In accordance with the Personal Data Ordinance, we have the right to charge a reasonable fee for the processing of any data access request. The person to whom requests for access to the kinds of data held can contact our customer service.',
	        	
	        	conditionscon811:'8.1 You will not use the V-Stars Services for any illegal, fraudulent or other prohibited activity. If V-Stars suspects that you may be engaging in or have engaged in a fraudulent, illegal or prohibited activity, including any violation of these Terms and Conditions, your access to the V-Stars Services and website may be suspended or terminated. Additionally, depending on the severity of the violations, we may contact law enforcement.',
	        	conditionscon812:'It is strictly forbidden to make or receive payments as consideration for or in connection with:',
	        	conditionscon813:'<span>•</span>Any illegal act; ',
	        	conditionscon814:'<span>•</span>Antiques; ',
	        	conditionscon815:'<span>•</span>Drugs, alcohol, or drug paraphernalia;',
	        	conditionscon816:'<span>•</span>Obscene or pornographic items, adult businesses or adult related services, including escort services, adult massage, or other adult-entertainment services, adult performer regardless of sexual orientation; ',
	        	conditionscon817:'<span>•</span>Digital currency;',
	        	conditionscon818:'<span>•</span>Forex or Binary or any other variation of trading; ',
	        	conditionscon819:'<span>•</span>Payday loans;',
	        	conditionscon8110:'<span>•</span>Debt elimination, consolidation, or reduction services;',
	        	conditionscon8111:'<span>•</span>Donations; ',
	        	conditionscon8112:'<span>•</span>Collection agencies;',
	        	conditionscon8113:'<span>•</span>Gambling or betting, including lottery tickets, casino gaming chips, off-track betting, memberships on gambling-related internet sites and wagers at races; ',
	        	conditionscon8114:'<span>•</span>Crowdfunding;',
	        	conditionscon8115:'<span>•</span>Peer to peer payments for personal purposes that are not related to business purposes; ',
	        	conditionscon8116:'<span>•</span>Precious metals and Rare earth minerals;',
	        	conditionscon8117:'<span>•</span>Pseudo-pharmaceuticals, Vitamins and supplements;',
	        	conditionscon8118:'<span>•</span>Insurance sales and services; ',
	        	conditionscon8119:'<span>•</span>Reselling prepaid cards or gift cards\certificates;',
	        	conditionscon8120:'<span>•</span>Prescription drugs;',
	        	conditionscon8121:'<span>•</span>Cigarettes, tobacco or e-cigarettes;',
	        	conditionscon8122:'<span>•</span>Internet, mail or telephone order pharmaceutical or pharmacy referral services;',
	        	conditionscon8123:'<span>•</span>Medical equipment, Prescription devices, controlled substances, unapproved drugs, unapproved medical devices; ',
	        	conditionscon8124:'<span>•</span>Medical or healthcare services, including services for medical treatment, rehabilitation, vaccination, health checks, psychological counselling, dietetics, plastic surgery, surrogacy and massage;',
	        	conditionscon8125:'<span>•</span>Items that promote hate, violence, racial intolerance, or the financial exploitation of a crime; ',
	        	conditionscon8126:'<span>•</span>Goods or services that infringe on the intellectual property rights of a third party; ',
	        	conditionscon8127:'<span>•</span>Live animals;',
	        	conditionscon8128:'<span>•</span>Fireworks;',
	        	conditionscon8129:'<span>•</span>Illegal Wildlife Trade;',
	        	conditionscon8130:'<span>•</span>Weapons (including without limitation, knives, guns, firearms or ammunition); ',
	        	conditionscon8131:'<span>•</span>Replica and/or unlicensed branded goods; ',
	        	conditionscon8132:'<span>•</span>Any other category restricted by Marketplaces;',
	        	conditionscon8133:'<span>•</span>Any other category or payer that V-Stars decides to prohibit, in its sole discretion.',
	        	
	        	
	        	conditionscon82:'8.2 You shall not use the V-Stars Services if you are residing, working or conducting business in any country restricted by the U.S. Office of Foreign Assets Control. We may in our sole discretion decide to discontinue or restrict our services to residents of other countries at any time and without prior notice.',
	        	conditionscon83:'8.3 We reserve the right to suspend or terminate your use of the V-Stars Services (including access to funds) at any time if we reasonably believe to be required to do so by law or in order to comply with recommendations issued by a relevant government authority or recognized body for the prevention of financial crime.',
	        	conditionscon84:'8.4 It is strictly forbidden to use the V-Stars Services for any illegal purposes including but not limited to fraud and money laundering. We will report any suspicious activity to the relevant law enforcement agency. You are prohibited from using the V-Stars Services in any attempt to abuse, exploit or circumvent any law or regulation.',
	        	conditionscon85:'8.5 If you conduct or attempt to conduct any transaction in violation of the prohibitions contained in this section or without the necessary approval from V-Stars, we reserve the right to (i) reverse the transaction; (ii) terminate or suspend your use of the V-Stars Services; (iii) report the transaction to the relevant law enforcement agency; and (iv) claim damages from you.',
	        	
	        	conditionscon911:'9.1 You agree that the following statements are true and accurate, and you acknowledge that we may refuse to process your transaction or even terminate our relationship if we find at any stage that they are not true and accurate:',
	        	conditionscon912:'<span>(i)</span> You are over the age of 18',
	        	conditionscon913:'<span>(ii)</span> You are duly registered in your place of incorporation or establishment and is legally subsisting',
	        	conditionscon914:'<span>(iii)</span> You have full authority to enter into this Agreement and services under it; ',
	        	conditionscon915:'<span>(iv)</span> You are the beneficial owner of the money being transferred;',
	        	conditionscon916:'<span>(v)</span> You are not acting on behalf of another person unless you have been properly authorized and verified by us;',
	        	conditionscon917:'<span>(vi)</span> You have all necessary authority to enter into the Transactions as well as the transactions contemplated in connection with or related to the V-Stars Services;',
	        	conditionscon918:'<span>(vii)</span> you have been operating in accordance with all applicable laws and regulations, and you have obtained all required and valid licences, consents, certificates and approvals (whether it is issued by government or in private) for the operation of your businesses, and you are not aware of any circumstances in which such licences, consents, certificates and approvals may be revoked, cancelled or not renewed;',
	        	conditionscon919:'<span>(viii)</span> Your use of the V-Stars Services will not infringe or misappropriate the intellectual property rights of any third party.',
	        	
	        	conditionscon92:'9.2 your use of the V-Stars Services will be in strict accordance with these Terms & Conditions and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the US or the country in which you reside); and ',
	        	
	        	conditionscon101:'10.1 You may terminate this Agreement at any time by notifying us in writing. ',
	        	
	        	conditionscon1021:'10.2 We may terminate this Agreement at any time by giving you one calendar months’ notice in writing. We may also terminate this Agreement immediately or on less notice, if we reasonably believe:',
	        	conditionscon1022:'<span>•</span> You have seriously or repeatedly broken the terms of this Agreement,',
	        	conditionscon1023:'<span>•</span> You have provided false information to us,',
	        	conditionscon1024:'<span>•</span> A service you have requested is connected to fraud , money laundering, terrorist financing, tax evasion, or other criminal activity,',
	        	conditionscon1025:'<span>•</span> It would mean we may otherwise break the law, regulation, code, or other duty that applies to us or may expose us to claims by third parties,',
	        	conditionscon1026:'<span>•</span> You threaten or are abusive to our staff,',
	        	conditionscon1027:'<span>•</span> You become bankrupt or insolvent or appear to be subject to an Insolvency Event.',
	        	
	        	
	        	conditionscon103:'10.3 Any complains about us or the services we provide should be addressed to us immediately by contacting V-Stars Customer Support or email us at complaints@vstarsfx.com. We may send an acknowledgement of complaint or request additional information from you regarding your complaint.',
	        	conditionscon104:'10.4 Our goal is to provide you with a prompt answer or resolution to your complaint where possible. Nothing contained herein, however, constitutes a commitment by V-Stars to resolve your complaint. ',
	        	conditionscon111:'11.1 V-Stars shall not be under any liability for any loss or damage resulting from delay or failure to perform either in whole or in part where such delay or failure is due to causes beyond our control, and/or not occasioned by our fault or negligence, including, but not limited to war, the threat of imminent war, riots or other acts of civil disobedience, insurrection, acts of God, restraints imposed by governments or any other foreign legal authority or any other industrial or trade disputes, fires, explosions, storms, floods, lightning, earthquakes, epidemic, pandemic and other natural calamities.',
	        	conditionscon112:'11.2 We assume no liability for any misrepresentations, mistakes, defaults, failures, omissions and whatsoever in the representations, statements or descriptions provided by us and/or any other third parties in any publications and materials relating to the goods and services provided or to be provided by us. Furthermore, we shall not be responsible or liable for the actions and omissions of third parties involved in the provision of the V-Stars Services.',
	        	conditionscon113:'11.3 Save and except as expressly provided in this agreement, we hereby disclaim all claims, responsibilities and liabilities (including any economic loss thereof) arising out of or in connection with the provision of the goods and services under the V-Stars services. We make no express or implied representations or warranties regarding our goods and services. Without limiting the foregoing, we do not warrant that the goods and services and the facilities used will be uninterrupted, without delay, error and defect-free, omission-free, or will meet any particular criteria of performance or quality. We expressly disclaim all express, implied or statutory warranties, including without limitation, warranties of merchantability, title, fitness for a particular purpose, non-infringement, compatibility, security accuracy, timeliness and completeness. in no event shall we be liable for any direct, indirect, incidental, special, exemplary, punitive, consequential or other damages whatsoever (including but not limited to liability for loss of use, data or profits), in whatever cause of any action, including but not limited to contract, negligence or other tortious actions, arising out of or in connection with the provision of the V-Stars services. we expressly exclude all liability for any damage or injury suffered directly or indirectly through the goods and services provided. ',
	        	conditionscon114:'11.4 Subject to and without prejudice to the foregoing, in the event that we are held liable for any loss or damage arising from or in connection with the V-Stars Services, the maximum amount of the damages that you may recover from us in aggregate shall not exceed the total amount of the Fees paid by you within the past twelve (12) months prior to the date of cause of the action arises. ',
	        	conditionscon115:'11.5 In respect of any Inbound Payment, you hereby release the Marketplace from liability for such payment as of when the Funds related thereto are received by V-Stars and not as of that later time when the Funds are settled to you by V-Stars. Each Marketplace shall be a third-party beneficiary under this provision. ',
	        	conditionscon116:'11.6 You acknowledge that V-Stars will provide the V-Stars Services using Service Providers. No commercial agreement exists between the Service Providers and yourself and each of the Service Providers will accordingly have no direct liability to you.',
	        	conditionscon117:'11.7 The V-Stars Services are provided “as is.” V-Stars and its Service Providers hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither V-Stars nor its Service Providers, makes any warranty that our Services will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, our Services at your own discretion and risk.',
	        	conditionscon118:'11.8 You agree to indemnify and hold harmless V-Stars and its Service Providers and their respective directors, officers, employees, and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the V-Stars Services, including but not limited to your violation of this V-Stars Terms & Conditions.',
	        	conditionscon119:'11.9 All of Section 10 of this V-Stars Terms & Conditions shall survive termination hereof.',
	        	conditionscon121:'12.1 If any provision of these Terms and Conditions is determined by a court, arbitral body or institution of competent jurisdiction to be invalid, illegal or unenforceable, such provision shall be reformed, modified and interpreted to make it valid, legal and enforceable and to most nearly approximate original intent of such provision, with the remainder of the Terms & Conditions remaining in full force and effect. ',
	        	conditionscon122:'12.2 No failure or delay by us in exercising any right, power or remedy under these Terms & Conditions shall operate as a waiver thereof, nor shall any single or partial exercise of the same preclude any further exercise thereof or the exercise of any other right, power or remedy. Without limiting the foregoing, no waiver by us of any breach of any provision hereof shall be deemed to be a waiver of any subsequent breach of that or any other provision hereof. ',
	        	conditionscon123:'12.3 The illegality, invalidity or unenforceability of any provision of these Terms and Conditions under the law of any jurisdiction shall not affect its legality, validity or enforceability under the law of any other jurisdiction nor the legality, validity or enforceability of any other provision.',
	        	conditionscon124:'12.4 You shall not assign or transfer any rights and obligations under these without our consent in writing. ',
	        	
	        	conditionscon1311:'13.1 In this V-Stars Terms and Conditions, the following terms shall have the following meaning:',
	        	conditionscon1312:'<span>“Agreement”</span>  means these general Terms and Conditions, together with all schedules and attachments forming the Agreement',
	        	conditionscon1313:'<span>“Business Day”</span>  means any day on which commercial banks in Hong Kong are generally available for service, except Saturdays, Sundays and public holidays.',
	        	conditionscon1314:'<span>“Buyer”</span>  means a person or entity that purchases your Product from you directly, or on a Marketplace.',
	        	conditionscon1315:'<span>“Customer”</span>  means in relation to the provisions of services under this Agreement, or commercial practices in relation to this Agreement, an individual who is acting or purporting to act, primarily for purposes that are related to the person’s trade or business.',
	        	conditionscon1316:'<span>“Customer Bank Account”</span>  means your designated beneficiary bank account in Hong Kong or the PRC into which you wish to receive Funds settled through us by using the V-Stars Services, and such bank account shall be specified by you in the V-Stars Account.',
	        	conditionscon1317:'<span>“Designated Payment Services”</span>  means (i) the US Payment Service; (ii) the EU Payment Service; and (iii) the Other Inbound Payment Service.',
	        	conditionscon1318:'<span>“EU”</span>  means the European Union.',
	        	conditionscon1319:'<span>“EU Payment Service”</span>  means the EUR payment services provided in V-Stars Services through the Single European Payment Area (“SEPA”) systems.',
	        	conditionscon13110:'<span>“EUR”</span>  means the Euro, the lawful currency of the EU.',
	        	conditionscon13111:'<span>“Fees”</span>  means the charges payable by you to us for using V-Stars Services.',
	        	conditionscon13112:'<span>“Funds”</span>  means funds received on your behalf by V-Stars or its Service Providers during the process of the V-Stars Services.',
	        	conditionscon13113:'<span>“Hong Kong”</span>  means the Hong Kong Special Administrative Region of the PRC.',
	        	conditionscon13114:'<span>“Inbound Payments”</span>  means any funds received by V-Stars via the Designated Payment Services.',
	        	conditionscon13115:'<span>“Marketplace”</span>  or <span>“Payer”</span>  means an e-commerce marketplace approved by V-Stars for acceptance with the V-Stars Services from time to time where you are a seller of Product pursuant to a written agreement between you and the Marketplace.',
	        	conditionscon13116:'<span>“Other Inbound Payment Service”</span>  means the payment services in currencies other than EUR and USD provided in V-Stars Services from time to time through a system designated by V-Stars.',
	        	conditionscon13117:'<span>“Other Locations”</span>  means locations other than the US and the EU where V-Stars provides Other Inbound Payment Service from time to time.',
	        	conditionscon13118:'<span>“PRC” </span> means the People’s Republic of China, and for the purpose of these Terms of Use, it does not include Hong Kong, the Macau Special Administrative Region and Taiwan.',
	        	conditionscon13119:'<span>“Product”</span>  means a product that you sell through a Marketplace and for which you wish to use the V-Stars Services to receive payment.',
	        	conditionscon13120:'<span>“Service Providers”</span>  means third parties providing facilities in the course of supplying the V-Stars Services by V-Stars, including but not limited to banks, payment service providers, clearing networks and other third party payment processing service providers.',
	        	conditionscon13121:'<span>“T&Cs”</span>  means the V-Stars Terms and Conditions set out in this Agreement.',
	        	conditionscon13122:'<span>“Transaction”</span>  means an actual or attempted payment transaction that involves V-Stars Services.',
	        	conditionscon13123:'<span>“V-Stars Account”</span>  means a unique account within the V-Stars Services established for you to register for and being able to the ongoing use of the V-Stars Services. For avoidance of doubt, such account shall not constitute a bank account. You are expected to provide your information, Marketplace store information, Transaction history and other information related to your use of the V-Stars Services.',
	        	conditionscon13124:'<span>“V-Stars Bank Account”</span>  means an operating account of V-Stars maintained at a financial institution in the US or the EU or Other Locations into which you shall be allowed to receive Funds through V-Stars as your agent under this Terms of Use. V-Stars shall inform you of the V-Stars Service Credentials once you have been approved for use of the V-Stars Services.',
	        	conditionscon13125:'<span>“US”</span>  means the United States of America.',
	        	conditionscon13126:'<span>“USD”</span>  means the United States dollars, the lawful currency of US.',
	        	conditionscon13127:'<span>“US Payment Service”</span> means the USD payment service provided in V-Stars Services through the Automated Clearing House (“ACH”) in the US.',
	        	
	        	credits:'PHOTO CREDIT',
	        	creditscon1:'We appreciate below designers sharing such eye-catching and creative works for us.',
	        	creditscon2:'Photos',
	        	creditscon3:'Photo by <a href="https://unsplash.com/photos/WMSvsWzhM0g?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Ruslan Bardash</a> on <a href="https://unsplash.com/search/photos/hong-kong?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
	        	creditscon7:'Photo by <a href="https://unsplash.com/photos/Oja2ty_9ZLM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Benjamin Davies</a> on <a href="https://unsplash.com/@bendavisual?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
	        	creditscon4:'Photo by <a href="https://www.pexels.com/">Pexels</a>',
	        	serviceotherpagesquestion:'Help',
	        	serviceotherpagescredits:'Photo Credits',
	        	serviceotherpagescreditstc:'Terms and Conditions',
	       		creditscon5:'Icons',
	       		creditscon6:'Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="CreativeCommons BY 3.0" target="_blank">CC 3.0 BY</a>',
	       },
	       ch: {
	          	navabout:'关于',
	          	navservices:'服务',
	          	navcontact:'联系',
	          	navhelp:'问题',
	          	navcareers:'职业生涯',
	          	login:'登陆',
	          	signup:'注册',
	          	en:'英文',
	          	ch:'中文',
	          	indextit:'V-STARS',
	          	indextit2:'您的海外收款伙伴',
	          	indextit3:'我们从海外市场赚钱更容易、更快捷、更便宜。',
	          	indexdiscover:'发现',
	          	indexwhy:'为什么选择v-star',
	          	indexwhycon:'作為一個電商賣家, 我們知道您有太多太多東西需要顧及, 從採購到物流, 從包裝到倉儲. 讓V-Stars的專業支付團隊分擔您的重擔, 讓您的資金流轉更有效率.',
	          	indexoffers:'V-Stars 提供',
	          	indexoffers1:'海外的本地銀行賬戶',
	          	indexoffers2:'優惠滙率',
	          	indexoffers3:'轉賬快捷',
	          	indexoffers4:'沒多餘收費',
	          	indexoffers5:'開戶簡單',
	          	indexoffers6:'24 / 7 網上服務 ',
	          	indexofferscon1:'讓您輕鬆收取在美國, 歐洲銷售平台的收款.',
	          	indexofferscon2:'讓您減低換滙損失, 把更多的收入帶回家.',
	          	indexofferscon3:'確保您可以盡快回款, 讓您的資金鏈更有效率.',
	          	indexofferscon4:'零開戶費, 零賬戶維護費, 零入賬費',
	          	indexofferscon5:'我們的客戶服務團隊確保您的注冊流程方便, 順暢.',
	          	indexofferscon6:'隨時操作網上轉賬, 輕鬆方便.',
	          	indexfees:'收費',
	          	indexfeestit1:'$0',
	          	indexfeestit2:'1%',
	          	indexfeesspan1:'           ',
	          	indexfeesspan2:'(或更低)',
	          	indexfeesscon1:'零注冊費, 零月費, 如果您需要更多的海外收款銀行賬戶, 我們也不額外收費',
	          	indexfeesscon2:'在我們拿到的市場滙率上按轉款額收取. 您轉款愈多, 我們收取愈少.',
				indexservices:'其它服務',
				indexservicestit1:'VAT',
				indexservicestit2:'供應商付款',
				indexservicescon1:'在歐盟國家銷售產品一般來說都需要繳交增值稅. V-Stars 可以幫您向稅務機關繳付增值稅.',
				indexservicescon2:'如果您需要支付在歐盟國家的供應商, V-Stars 可以讓您輕鬆完成支付.',
				indexpates:'我們的滙率',
	          	indexpatescon:'我們讓您緊貼滙率走勢, 讓您在市場領先一步.',
	          	indexpatestit1:'實時滙率與圖表',
	          	indexpatestit2:'滙率到價提醒',
				indexworks:'如何操作',
	          	indexworkstit1:'注冊',
	          	indexworkstit2:'連接銀行賬戶',
	          	indexworkstit3:'轉賬 ',
	          	indexworkscon1:'點擊”注冊”, 然後按程序完成注冊. 我們的客戶服務團隊會盡快跟您聯繫.',
	          	indexworkscon2:'將我們提供給您的海外本地銀行賬戶資料輸入到您想收款的海外銷售平台, 然後開始收款.',
	          	indexworkscon3:'轉賬 – 隨時登錄網上平台進行轉款操作, 我們會盡快把錢轉到您手上.',
				footer1:'V-star有限公司2023',
	          	footer2:'智博源出品',
	          	
	          	aboutus:'關於我們',
	          	aboutuscon1:'V-Stars 由一班在支付領域經驗豐富的團隊創立. 我們非常了解中國的海外賣家, 尤其是中小企業, 在海外銷售產品的時候, 往往在收款時遇到成本高, 時間長的問題.',
	          	aboutuscon2:'我們希望可以協助海外賣家, 讓他們的海外收款<i>更快</i>, <i>更平</i>, <i>更簡單</i> .',
	          	abouthistory:'歷史',
	          	abouthistorytit1:'2018年8-9月',
	          	abouthistorytit2:'2018年5月',
	          	abouthistorytit3:'2018年1月',
	          	abouthistorytit4:'2017年12月',
	          	abouthistorytit5:'2017年11月',
	          	abouthistorytit6:'2017年8月',
	          	abouthistorytit7:'2016年8月',
	          	abouthistorycon1:'IT系統完成最後測試, 準備上線',
	          	abouthistorycon2:'成功在銀行開設賬戶, 用以處理客戶資金, 該銀行賬戶與V-Stars 公司的營運賬戶獨立分開',
	          	abouthistorycon3:'取得香港金錢服務經營者牌照',
	          	abouthistorycon4:'搬到尖沙咀美麗華商場的辦公室, 可容納30人',
	          	abouthistorycon5:'跟北京IT團隊合作, 開始建立內部IT系統(前端/後台)',
	          	abouthistorycon6:'拿到投資資金開展業務',
	          	abouthistorycon7:'公司注冊',
	          	aboutjoin:'加入我们',
	          	aboutjoincon1:'我們相信不論是支付公司還是貿易公司 – 員工都非常重要. 只有當員工能熱愛他們的工作, 他們才可以創造佳績. 我們為員工提供開放友好的工作環境和空間, 希望員工之間可以自由溝通, 讓工作更順利完成.',
	          	aboutjoincon2:'<i>這裡沒有等級之分. 沒有官僚主義. 沒有從上而下的管理制度.</i>',
				aboutvalue:'對員工的期望',
	        	aboutvaluetit1:'合作',
	        	aboutvaluetit2:'尊重',
	        	aboutvaluetit3:'幫助',
	        	aboutvaluetit4:'好奇心',
	        	aboutvaluetit5:'勇敢',
	        	aboutvaluetit6:'信任',
	        	aboutvaluecon1:'我們重視團隊合作精神. 有才能的人一起合作才能產生協同效應.',
	        	aboutvaluecon2:'您可能是剛加入的初級員工, 或者是經驗富的資深員工. 我們都樂於聆聽您們提出的建議, 並希望您可以隨時提出來.',
	        	aboutvaluecon3:'樂於幫助身邊的同事, 亦敢於隨時向別人求助.',
	        	aboutvaluecon4:'很多時候一個非常棒的建議都是來自於一些非常簡單的問題. 保持您的好奇心, 隨時發問.',
	        	aboutvaluecon5:'我們鼓勵員工挑戰前設, 對他們覺得不合理或不正確的事情提出質疑, 並敢於帶出改變.',
	        	aboutvaluecon6:'我們相信每個員工都有自主完成工作的能力, 並做出成綪. 我們不認為公司需要監督員工所做的每一項大小事情.',
				aboutbenefits:'我們的福利',
	        	aboutbenefitstit1:'大方的年假',
	        	aboutbenefitstit2:'彈性工作時間',
	        	aboutbenefitstit3:'醫療保險',
	        	aboutbenefitstit4:'公司資助的團隊活動',
	        	aboutbenefitstit5:'舒適開放的工作環境',
	        	aboutbenefitstit6:'免費早餐',
				aboutpayment1:'支付经理',
	        	aboutpayment2:'KYC专家 ',
	          	
				services:'服务',
	        	servicestit:'V-STARS平台支付',
	        	servicescon1:'海外銷售平台收款從此變得簡單, 快捷, 平宜. ',
	       		servicescon2:'V-Stars 為您的資金回款護航, 助您業務更上一層.',
	       		servicesvat:'增值稅',
	       		servicesvatcon:'賣家亦可利用V-Stars 為他們所開設的美元或歐元的本地虛擬銀行賬戶裡的餘額向歐盟國家稅局繳付增值稅',
	       		servicesadvantagetit1:'簡單',
	        	servicesadvantagetit2:'透明',
	        	servicesadvantagetit3:'省錢',
	        	servicesadvantagetit4:'省時',
	        	servicesadvantagecon1:'好的產品一般都方便易用. 我們的支付方案也是如此.',
	        	servicesadvantagecon2:'我們的收費透明直接, 用家能清楚掌握成本.',
	        	servicesadvantagecon3:'我們的是透過幫助賣家省錢從中賺取收入. 我們相信共贏才能讓一家企業長久生存下來.',
	        	servicesadvantagecon4:' “時間就是金錢”這句話尤其適用於海外銷售的賣家, 因為銷售週期可以長達數月, 我們希望可以幫助賣家更快完成收付款.',
	       		
				contacthear:'我们很乐意收到你的来信！',
	        	contactcon:"我们很乐意收到你的来信！有问题或反馈吗？请用下面的表格联系我们，我们会尽快回复您。",
				contacthotline:'用户服务热线',
				contactemail:'邮箱',
				contactphone:'拨号电话',
				contacthotlinecon:'香港弥敦路132号米拉广场A座1114-16单元',
				contactemailcon:'enquiry@vstarsfx.com',
				contactphonecon:'852-3793-3400 (HK)',
	       		contactleavemessage:'留言',
	        	name:'姓名*',
				tel:'电话*',
				subject:'话题*',
				message:'消息*',
	        	send:'发送',
	        	
	        	question:'问题',
	        	registration:'登记',
	        	feesandcharges:'费用及收费',
	        	accountoperations:'账户操作',
	        	security:'安全性',
	        	registrationtit1:'完成整个注册需要多长时间？',
	        	registrationtit2:'我什么时候可以从市场上获取我的虚拟银行账户的详细信息？',
	        	registrationtit3:'我需要提供什么样的文件来完成我的注册？',
	        	registrationtit4:'在注册过程中是否有我需要提供的信息？',
	        	registrationtit5:'有挂号费吗？',
	        	registrationtit6:'V-STARS提供哪种货币的银行账户？',
	        	registrationtit7:'什么样的市场可以使用虚拟银行账户来筹集资金？',
	        	registrationtit8:'我能通过我的贝宝账户从易趣网收到钱吗？',
	        	registrationcon1:'如果您能提供我们员工所需的所有信息和文件，我们将在同一天完成开户。',
	        	registrationcon2:'一旦您的注册完成，我们的帐户经理将与您联系的方式，并向您发送虚拟银行帐户的细节。',
	        	registrationcon3:'如果你注册为唯一的交易者：',
	        	registrationcon4:'<span>•</span>照片识别证明',
	        	registrationcon5:'<span>•</span>三个月内发出地址证明',
	        	registrationcon6:'如果你注册为一家公司：',
	        	registrationcon7:'<span>•</span>注册证书',
	        	registrationcon8:'<span>•</span>关于公司董事和股东的最新信息',
	        	registrationcon9:'<span>•</span>董事和股东的照片身份证明和地址证明',
	        	registrationcon10:'是的，你需要提供关于你预期的交易量、唯一的商品类型和你打算从中筹集资金的市场的信息。我们的员工会指导你完成这个过程，不用担心。',
	        	registrationcon11:'不，注册是免费的。',
	        	registrationcon12:'我们目前只提供欧洲银行账户和美元银行账户。欧洲银行账户可以接收SEPA支付，美元银行账户可以接收ACH支付。',
	        	registrationcon13:'虚拟银行账户可以用来从大部分市场筹集资金，但你必须在启动任何资金收集之前将市场的店面链接发送给我们进行检查。如果你是一个B2B卖家，请让我们知道之前，当你的买家将支付你的钱到虚拟银行帐户。',
	        	registrationcon14:'是的，你可以，但再次，你必须提供相关的店面链接和贝宝交易记录，我们检查之前，你这样做。',
	        	feesandchargestit1:'V-STARS如何向客户收费？',
	        	feesandchargestit2:'如果我在虚拟银行账户收到美元，我可以把美元转回我自己的账户，不做任何货币转换吗？',
	        	feesandchargestit3:'V-STARS能给我少于0.7%的费用吗？',
	        	feesandchargestit4:'V-STARS是有竞争力的汇率吗？',
	        	feesandchargestit5:'我需要转账的最低金额是多少？',
	        	feesandchargescon1:'我们向客户收取从虚拟银行账户到银行账户的转账。交易金额最高收取0.7%的手续费。除此之外，我们不收取任何费用。',
	        	feesandchargescon2:'你不必兑换你所收到的货币，但如上所述，交易金额最多要收取0.7%的手续费。',
	        	feesandchargescon3:'你越是与我们交易，我们就越低。请与您的帐户经理联系，当你与我们交易了一段时间，想看看你是否可以得到较低的费用。',
	        	feesandchargescon4:'是的，我们得到了个人客户通常无法从我们的合作伙伴那里获得的银行间汇率。',
	        	feesandchargescon5:'您至少要转换500美元/欧元。',
	        	accountoperationstit1:'我怎样办理转账手续？',
	        	accountoperationstit2:'我如何为自己的账户输入我的银行资料？',
	        	accountoperationstit3:'支付我的银行账户需要多长时间？',
	        	accountoperationscon1:'在你进行转账之前，你必须登录到你的V-STAR账户并添加你自己的银行账户的详细信息。然后你可以通过在线系统随时转移你的余额。',
	        	accountoperationscon2:'登录到你的V-STARS账户，点击“创建一个新的受益者”。输入所需的细节，然后将通过我们来验证。请注意，受益人可以是您自己的帐户，或在税务机关的名义，如果你正在支付增值税。',
	        	accountoperationscon3:'通常需要1-2个工作日。在极少数情况下，可能会发生延误。V星将尽一切可能确保资金按时到位，但不承担由中介或接收银行造成的延误。',
	        	securitytit1:'V-STARS如何确保我的钱是安全的？',
	        	securitytit2:'我的个人信息保护得很好吗？',
	        	securitytit3:'如果我忘记密码怎么办？',
	        	securitycon1:'确保您的钱的安全和安全是我们业务最重要的部分。我们保证你的资金与商业基金隔离。',
	        	securitycon2:'我们在香港由香港海关和货币服务监管局监管。我们需要持有足够的资金来保护我们的业务，保护我们的客户。',
	        	securitycon3:'V-STARS具有安全系统，以保护客户信息免受未经授权的访问。我们不会将你的个人信息分享给任何第三方以外的条款和条件。请仔细阅读，如果您有任何疑问，请告诉我们。',
	        	securitycon4:'点击“忘记密码”在网页中的V-STAR日志，并按照指示重置密码',
	        	
	        	paymentmanager:'支付经理',
	        	paymentques1:'关于V-star',
	        	paymentans11:'我们刚刚开始涉足B2C和B2B支付行业。我们收到了新的资金，希望开始我们的生意。',
	        	paymentans12:'我们目前正在寻找一个付款和运营经理，以帮助我们建立和测试我们的系统，并负责支付操作后，系统去现场。您将在我们支付系统的架构中扮演重要角色，它将每天处理数以百计甚至数以千计的交易',
	        	paymentques2:'工作要求:',
	        	paymentans21:'系统运行前:',
	        	paymentans22:'<span>•</span>与IT团队一起设计和测试付款系统',
	        	paymentans23:'<span>•</span>建立并维护付款手册，记录操作程序并确保有足够的控制。',
	        	paymentans24:'系统运行后:',
	        	paymentans25:'<span>•</span>确保及时处理交易和执行客户付款并解决整个过程中的任何问题',
	        	paymentans26:'<span>•</span>盖住打开的位置，检查交易是否被正确预订',
	        	paymentans27:'<span>•</span>与其他团队合作，确保付款过程的顺利和准确',
	        	paymentans28:'<span>•</span>编制定期报表，如卷、收入、损益计算等',
	        	paymentans29:'<span>•</span>与付款方对应的付款问题',
	        	paymentans210:'<span>•</span>银行往来帐户核对',
	        	paymentans211:'<span>•</span>付款调查及追踪查询',
	        	paymentans212:'<span>•</span>确保所有结算业务及时、正确处理',
	        	paymentans213:'<span>•</span>作为付款问题的联络点',
	        	paymentans214:'<span>•</span>拓展和发展付款团队',
	        	paymentques3:'我们正在寻找什么:',
	        	paymentans31:'<span>•</span>至少3年的付款工作经验',
	        	paymentans32:'<span>•</span>良好的付款系统知识',
	        	paymentans33:'<span>•</span>良好的数字意识和细节意识，善于处理数字问题。',
	        	paymentans34:'<span>•</span>主动寻找更好的解决方案',
	        	paymentans35:'<span>•</span>心胸开阔，友好（与其他团队沟通，领导自己的团队）',
	        	paymentans36:'<span>•</span>讲商务普通话',
	        	paymentques4:'我们能提供什么:',
	        	paymentans41:'<span>•</span>有竞争力的薪水，与经验相称',
	        	paymentans42:'<span>•</span>18天年假',
	        	paymentans43:'<span>•</span>酌情奖金',
	        	paymentans44:'<span>•</span>强积金与健康保险覆盖面',
	        	paymentans45:'<span>•</span>弹性工作时间',
	        	paymentans46:'<span>•</span>开放友好的工作环境',
	        	paymentcontact:'如果您有兴趣申请这个职位，并希望在您的职业生涯中接受新的挑战，请将您的简历（in .doc或pdf）发送到<span>CaleSers@ vStasfx.com</span>。',
	        	
	        	
	        	kycspecialist:'KYC专家',
	        	kycques1:'关于V-Stars',
	        	kycans11:'我们刚刚开始涉足B2C和B2B支付行业。我们收到了新的资金，希望开始我们的生意。如果你正在寻找一个新的挑战，在你的事业和发挥作用，请加入我们的旅程。',
	        	kycans12:'我们目前正在寻找一个了解您的客户（KYC）专家，以帮助我们在我们的客户顺利和有效的方式。您将代表V-星与客户沟通，并收集识别文件，以满足合规要求',
	        	kycques2:'职位要求:',
	        	kycans21:'<span>•</span>协助KYC系统的测试',
	        	kycans22:'<span>•</span>通过电子邮件和电话与客户沟通，收集身份证明文件和其他相关信息',
	        	kycans23:'<span>•</span>检查并完成每个客户的KYC文件，以符合批准',
	        	kycans24:'<span>•</span>响应合规团队对客户档案的询问',
	        	kycans25:'<span>•</span>保持客户的登机率和客户满意度',
	        	kycans26:'<span>•</span>报告可疑情况',
	        	kycans27:'<span>•</span>对KYC工艺的改进建议',
	        	kycques3:'我们正在寻找什么:',
	        	kycans31:'<span>•</span>普通话流利 ',
	        	kycans32:'<span>•</span>商务英语',
	        	kycans33:'<span>•</span>超级友好，超级耐心',
	        	kycans34:'<span>•</span>关注细节',
	        	kycans35:'<span>•</span>对KYC/AML要求的基本理解',
	        	kycans36:'<span>•</span>良好的沟通能力，能以简单的方式解释需求',
	        	kycques4:'我们能提供什么:',
	        	kycans41:'<span>•</span>有竞争力的薪水，与经验相称 ',
	        	kycans42:'<span>•</span>18天年假',
	        	kycans43:'<span>•</span>酌情奖金',
	        	kycans44:'<span>•</span>强积金/健康保险覆盖率',
	        	kycans45:'<span>•</span>弹性工作时间',
	        	kycans46:'<span>•</span>开放友好的工作环境',
	        	
	        	conditionstit:'V-Stars 条款 (v1.0)',
	        	conditionstit1:'1. 关于V-Stars',
	        	conditionstit2:'2. 范围',
	        	conditionstit3:'3. 登记处',
	        	conditionstit4:'4. 服务',
	        	conditionstit5:'5. 资金来源',
	        	conditionstit6:'6. 结算',
	        	conditionstit7:'7. 维护与安全',
	        	conditionstit8:'8. 禁止交易',
	        	conditionstit9:'9. 表示与保证',
	        	conditionstit10:'10. 合同终止与投诉',
	        	conditionstit11:'11. 责任、赔偿和免责声明',
	        	conditionstit12:'12. 其他',
	        	conditionstit13:'13. 定义',
	        	conditionscon11:'V-Stars有限公司（“V-Stars”、“我们”、“我们”、“我们公司”）是一家在香港注册的有限责任公司。我们也被注册为香港海关的货币服务运营商。我们的官方网站是：<i>www. vStasfx.com</i>。',
	        	conditionscon21:'2.1 这里列出的条款和条件（“T＆CS”）适用于您注册V-Stars，并使用我们的支付服务。请仔细阅读，确保你已经理解了内容。您将被要求接受并同意在注册后的条款和条件。如有任何疑问，请与我们联系。',
	        	conditionscon22:'2.2 V-Stars可以定期修改T＆CS由于监管的变化或其他业务原因。我们将通过电子邮件通知您，如果有任何变化的T＆CS，您可以随时检查最新版本的T＆CS在我们的官方网站。除非另有说明，否则更改将立即生效。在T＆CS的任何更改之后，您继续使用我们的服务构成您同意的变更。',
	        	conditionscon23:'2.3 T＆CS应受香港法律的管辖和解释。各方同意不可撤销地服从香港法院的专属管辖权。',
	        	conditionscon24:'2.4  我们可以随时将这些TC和CS翻译成其他语言，以供参考和信息使用。如英文版本与其他语言版本不一致或冲突，以英文版本为准。',
	        	conditionscon31:'3.1 公司或个人可以在我们的官方网站上注册使用V-Stars服务。在访问或使用任何V-Stars服务之前，我们需要打开一个V-Stars账户，为此，客户需要不时提供由V-Stars请求的信息和文件。在开放期间，我们将有权要求任何额外的信息和文件，包括但不限于，你的董事和股东的信息，以及你的业务性质，公司和财务信息。',
	        	conditionscon32:'3.2 在提供此类信息时，您应随时通过电子邮件或通过我们指定的系统或渠道及时通知我们任何更改。通过请求打开一个V-Stars帐号，您将被视为同意V-Stars，以验证您的注册信息对第三方数据库。',
	        	conditionscon33:"3.3 如果你代表公司注册V-Stars服务，你必须在商业实体的形成文件和/或在适用法律下以其他方式被法律授权。",
	        	conditionscon34:'3.4 V-Stars保留所有权利开放或拒绝的V-Stars帐户任何公司或个人。V-Stars还保留在任何时间终止任何V-Stars账户的权利。在不成功的申请或终止的情况下，V-Stars没有义务提供任何理由。',
	        	conditionscon35:'3.5 如果您的V-Stars帐户成功打开，V-Stars将通过电子邮件通知您，我们将为您提供您的V-Stars登录凭据在这样的电子邮件中。您的登录凭据是独一无二的，您有责任保持这些信息的安全。你必须总是采取合理的步骤来保持你的V-Stars帐号的用户名和密码的安全和严格保密，你永远不应该透露给任何人。如果您发现任何未经授权使用或进入您的V-Stars帐户，您应立即通知我们。通过使用正确的用户名和密码访问V-Stars帐户，应认为该帐户已被合法访问并在您的授权下进行，并且您同意对此类使用所产生的交易和费用承担责任。',
	        	conditionscon41:'4.1 V-Stars服务由您组成，通过V-Stars作为您的代理从市场上接收V-Stars银行账户中的资金。V-Stars是一个独立的承包商，只作为您的代理，收款人在资金方面。V-Stars不代表受托人、受托人或代管持有人。',
	        	conditionscon42:'4.2 V-Stars对任何买方或市场或对任何产品或任何其他业务部分不承担任何责任。你对你的产品、买主和市场承担唯一责任，并应赔偿和持有V-Stars，其董事、官员、雇员和代理人不受任何人反对V-Stars的任何索赔。',
	        	conditionscon43:'4.3 V-Stars账户和相关的V-Stars服务仅用于接收来自市场的入站付款，并将其汇入客户银行账户。你不应该让市场有权借记V-StarsR银行账户，而你将对市场或任何其他第三方在此类账户上的任何借记承担责任。',
	        	conditionscon44:'4.4 V-Stars将使用合理的努力通知你的任何入站资金进入V-Stars银行帐户通过你的V-Stars帐户。V-Stars不能保证这样的信息是准确的、完整的或及时的。',
	        	conditionscon45:'4.5 V-Stars有权从任何结算给您抵消任何由您欠V-Stars基金，包括但不限于，所有费用在该T＆CS或以其他方式支付。',
	        	conditionscon46:'4.6 在使用V-Stars服务之前，您可能需要向V-Stars提供额外的信息和文档。这些附加信息可能包括允许V-Stars验证实体股东身份的文件。附加信息包括但不限于支持交易数据和来自市场的支付确认。未能提供这样的请求信息可能会导致我们拒绝使用V-Stars服务。',
	        	conditionscon47:'4.7 如果V-Stars或其服务提供商确定拟议的交易、转让、汇款或结算可能违反任何适用的法律或法规，则可暂时扣留资金。根据适用法律、法规的要求，可以没收资金。',
	        	conditionscon48:'4.8 在我们的服务下分配的V-Stars银行账户不是典型的银行账户，也不提供银行账户的特征和好处。客户在V-Stars银行账户上没有存款利息。',
	        	conditionscon49:'4.9 资金是你的财产。除注册用户以外，任何人或实体都不享有与基金有关的任何权利。您不得转让或转让您的权利，利用V-Stars服务的第三方或以其他方式授予任何第三方法律或公平的利益与你使用的V-Stars服务。',
	        	conditionscon410:'4.10 使用我们的服务需要事先登记与V-Stars。你同意给我们提供完整、准确的注册信息。V-Stars服务旨在启用支付与电子商务相关的活动，不用于个人或非法使用。',
	        	conditionscon411:'4.11 你完全负责与V-Stars服务有关的所有适用的政府税，包括但不限于销售和购买产品所产生的税收、所收到的资金和所有相关的纳税申报义务。',
	        	conditionscon412:'4.12 如果您的V-Stars账户在六年以上（6年）内没有交易或闲置，则V-Stars账户中剩余的资金将被视为被您放弃，我们可能会丧失这些资金。',
	        	conditionscon413:'4.13 我们保留在任何时候终止您的V-Stars服务的权利，您可以随时取消您的V-Stars服务。严禁使用V-Stars服务，包括但不限于欺诈和洗钱等非法用途。禁止在任何企图滥用、剥削或规避任何法律或法规的情况下使用V-Stars服务。',
	        	conditionscon51:'5.1 我们的V-Stars银行帐户使您能够从市场上获得资金。V-Stars银行帐户目前可在美元和欧元，我们可能会启用额外的货币不时。你应该确保通过V-Stars银行账户结算资金不会违反你与市场的协议。只有V-Stars认可的市场才可以向你的V-Stars银行账户付款。市场的认可是V-Stars的唯一和绝对的自由裁量权。在使用V-Stars银行账户之前，你应该申报你要接收的市场。任何不被V-Stars认可的市场发送的入境付款可能会被拒绝。任何与拒付款项相关的费用和费用应由你承担。',
	        	conditionscon52:'5.2 在注册的V-Stars，您将提供银行信息，您可能需要从市场上获得资金。你应该向你希望收到付款的市场提供信息。',
	        	conditionscon53:'5.3 V-Stars银行账户不是银行账户，您不应尝试使用V-Stars银行账户作为银行账户。您同意避免与任何支持V-Stars服务的银行或服务提供商直接通信。任何与银行或其他提供商直接联系的V-Stars服务可能导致立即终止使用V-Stars服务。',
	        	conditionscon54:'5.4 V-Stars美元银行账户将只接受通过Ach信用转让从认可市场接收的资金。欧洲银行账户只接受从欧洲经济区批准的市场通过SEPA信用转移获得的资金。其他货币的其他入站付款也可以通过V-Stars不时启用。',
	        	conditionscon55:'5.5 V-Stars不支持任何现金，信用卡支付，电汇或支票入境支付。我们保留在任何时候拒绝和返还部分或全部入站付款的权利。付款可能因任何原因被拒绝，包括但不限于与遵守银行保密法/反洗钱/外国资产管制条例办公室或V-Stars遵守政策有关的原因。当拒绝或返回付款时，我们将没有义务披露拒绝的细节。',
	        	conditionscon56:'5.6 入境付款到达V-Stars的时间不在我们的控制范围之内。如果在五（5）个工作日内没有收到入站付款，我们将为您提出内部调查，因为您已经向我们提出了这样的要求。任何与市场有关的问题或争端，其政策应由市场直接解决，而不是V-Stars的责任。',
	        	conditionscon57:'5.7 V-Stars在我们的官方网站上公开了它的费用和收费，或者你可以在登录到你的V-Stars账户时进行具体的检查。根据交易量，V-Stars采用分层收费结构。V-Stars也可以提供形式的促销或退款，减少费用和奖金。V-Stars服务的收费有时会在V-Stars唯一和绝对自由裁量权上进行修正。如果您有任何问题或不清楚任何费用，您应该联系V-Stars客户服务。 ',
	        	conditionscon58:'5.8 未经V-Stars认证的付款人发送的入站付款将被拒绝并返还。任何与退款相关的费用和费用应由你或付款人承担，无论何种情况适用。如果因任何原因拒付，银行或其他支付方可收取费用。你只负责与拒绝付款有关的任何费用。 ',
	        	conditionscon61:'6.1 为了完成您的资金结算到您的客户银行帐户，您必须登录到您的V-Stars帐户，并要求基金结算。您需要提供您的客户银行账户的银行账户细节。除非你向政府当局交税，否则你不能要求任何与你的V-Stars账户名称不一样的客户银行账户结算。',
	        	conditionscon62:'6.2 您必须确保您的客户银行帐户信息是正确和准确的。由于您提供不正确的付款细节，我们不能对资金被发送到错误的银行账户负责。如果因为这样的原因拒付，银行的费用可能会从你的客户余额中扣除。如有不正确或错误的付款，我们将采取合理的措施，协助您追踪，并在合理的情况下，收回此类付款，但我们将不承担任何不能收回的款项。',
	        	conditionscon63:'6.3 V-Stars可能依赖于第三方银行同行或本地支付提供商，我们有付款安排，并在中国进行监管，并遵守当地法律完成结算。',
	        	conditionscon64:'6.4 V-Stars将开始解决你的客户银行帐户的金额，你解决，少任何适用的费用。您的客户银行账户所收取的任何费用都不是V-Stars的责任。',
	        	conditionscon65:'6.5 如果市场要求的话，或者如果V-Stand认为它是唯一必要的，那么V-Stars可以通过V-Stars提供商家证据交易基金的收据。商家授权V-Stars提供该协议的副本以及交易信息，以向请求VoStAR银行账户的商家或定居点的任何市场提供交易信息。',
	        	conditionscon71:'7.1 您必须确保您的信息与V-Stars记录始终是准确和最新的，我们将不承担任何损失，因为你没有这样做。我们随时可以要求您确认您的信息的准确性或提供文件或其他证据来核实这些信息。',
	        	conditionscon72:'7.2 我们可以通过电子邮件、电话或其他方式与您联系，关于您使用V-Stars服务的信息或通知。你有责任定期检查你的V-Stars帐号和你的电子邮件帐号的正确运作或你提供给V-Stars的其他通信方式，并及时检索并阅读由V-Stars或其工作人员发送的信息。您将只负责因您未能提交或通知我们更改您的联系细节直接造成的任何损失。',
	        	conditionscon73:'7.3 有关付款，取款和其他V-Stars服务活动的信息可在您的V-Stars帐户，您可以通过我们的官方网站登录。您可以在事务历史中找到每个事务的详细信息。',
	        	conditionscon74:'7.4 月报表将在每月结束后10个工作日内由我们准备。这样的月报表可以直接发送到您的电子邮件或登录后在我们的网站上可用。我们强烈鼓励你定期核对这项声明。如在该声明之日起30日内未收到任何书面通知，则应视为正确和结论性。',
	        	conditionscon75:'7.5 如果你的V-Stars账户在过去的六个月内没有活动，我们可能会认为你是不活跃的。一旦你被视为不活跃，我们将禁用某些特征和服务在你的V-Stars帐户，甚至可能暂停你使用的V-Stars服务。如果你被认为是不活跃的，你可以要求V-Stars反应你的状态。V-Stars明星可以反应你的地位，在其唯一的自由裁量权。你也可能被要求给我们新的文件作为重新验证的目的。',
	        	conditionscon76:'7.6 你还必须采取一切合理的措施，使你的保密程序保密和安全，你必须采取一切合理的措施，防止损失，盗窃或欺诈滥用。我们将作出合理的努力，以保护您的个人信息免受意外损失和未经授权的访问，使用或披露。然而，我们不能保证未经授权的第三方永远无法获得不正当目的的此类个人信息。你承认有这样的风险，愿意自费承担。如果你知道或怀疑你的安全程序已经丢失，被盗或挪用，或有未经授权的交易或支付或其他安全漏洞，你必须立即通知我们。',
	        	
	        	conditionscon771:'7.7 我们收集的个人资料可用于下列目的：',
	        	conditionscon772:'<span>a)</span> 按照客户提供的条款和条件，进行日常的支付服务、电汇及相关服务；',
	        	conditionscon773:'<span>b)</span> 进行核查检查；',
	        	conditionscon774:'<span>c)</span> 协助其他金融机构（包括银行和服务提供商）进行检查；',
	        	conditionscon775:'<span>d)</span> 为客户的使用设计金融服务或相关产品；',
	        	conditionscon776:'<span>e)</span> 营销明星服务与产品；',
	        	conditionscon777:'<span>f)</span> 符合要求的信息披露的要求，任何法律约束V-Stars.',
	        	conditionscon781:'7.8 V-Stars公司持有的个人资料将保密，但我们可以将上述信息提供给以下各方（无论是在香港境内还是在境外',
	        	conditionscon782:'<span>a)</span> 任何第三方服务提供商，为其业务的运作提供V-Stars的管理、电信、计算机、支付清算或其他服务；',
	        	conditionscon783:'<span>b)</span> 对承诺承担保密义务的V-Stars负有保密义务的其他人；',
	        	conditionscon784:'<span>c)</span> 银行往来方和受益人银行或服务提供者，就本条款提供的服务提供必要的账户信息；',
	        	conditionscon785:'<span>d)</span> 你的被授权的用户或其他代表为本条款提供服务的人；',
	        	conditionscon786:'<span>e)</span> 在任何法律约束下，V-Stars有义务向我们或根据其规定的规章或其他当局发出的任何指引的要求作出披露的义务。',
	        	
	        	
	        	conditionscon79:'7.9 我们不出售任何我们持有的个人资料。如果您不希望我们使用您的个人资料直接销售目的，请在注册期间指出您的异议，不要勾选相关框，因为它代表您目前是否接受直接营销联系或信息的选择。',
	        	conditionscon710:'7.10 我们将只保留您的个人资料，只要有必要，但一般不超过六年后，我们与您的业务关系。根据《个人资料条例》，我们有权收取处理任何资料存取请求的合理费用。请求访问所持数据类型的人可以联系我们的客户服务。',
	        	
	        	conditionscon811:'8.1 你不会对任何非法、欺诈或其他禁止活动使用V-Stars服务。如果V-Stars怀疑你可能从事或从事欺诈、非法或禁止的活动，包括违反这些条款和条件，你可以进入或终止V-Stars服务和网站。此外，根据违规行为的严重程度，我们可以联系执法部门。',
	        	conditionscon812:'严禁制作或接收付款，作为与之相关的考虑：',
	        	conditionscon813:'<span>•</span>任何违法行为；',
	        	conditionscon814:'<span>•</span>古董；',
	        	conditionscon815:'<span>•</span>药物、酒精或药物用品；',
	        	conditionscon816:'<span>•</span>淫秽或色情物品、成人企业或成人相关服务，包括护送服务、成人按摩或其他成人娱乐服务，成人表演者不顾性取向；',
	        	conditionscon817:'<span>•</span>数字货币；',
	        	conditionscon818:'<span>•</span>外汇或二进位或任何其他交易变动；',
	        	conditionscon819:'<span>•</span>发薪日贷款；',
	        	conditionscon8110:'<span>•</span>债务消除、合并或减少服务；',
	        	conditionscon8111:'<span>•</span>捐赠；',
	        	conditionscon8112:'<span>•</span>托收机构；',
	        	conditionscon8113:'<span>•</span>赌博或投注，包括彩票、赌场游戏筹码、场外投注、赌博相关网站的会员资格和比赛赌注；',
	        	conditionscon8114:'<span>•</span>众筹资金；',
	        	conditionscon8115:'<span>•</span>与商业目的无关的个人目的的对等支付；',
	        	conditionscon8116:'<span>•</span>贵金属和稀土矿物；',
	        	conditionscon8117:'<span>•</span>假药、维生素和补充剂；',
	        	conditionscon8118:'<span>•</span>保险销售和服务；',
	        	conditionscon8119:'<span>•</span>倒卖预付卡或礼品卡、证书；',
	        	conditionscon8120:'<span>•</span>处方药；',
	        	conditionscon8121:'<span>•</span>香烟、烟草或电子香烟；',
	        	conditionscon8122:'<span>•</span>互联网、邮件或电话订购药品或药房转诊服务；',
	        	conditionscon8123:'<span>•</span>医疗设备、处方设备、受控物质、未经批准的药品、未经批准的医疗器械；',
	        	conditionscon8124:'<span>•</span>医疗或保健服务，包括医疗、康复、预防接种、健康检查、心理咨询、饮食、整形外科、代孕和按摩等服务；',
	        	conditionscon8125:'<span>•</span>促进仇恨、暴力、种族不容忍或金融剥削犯罪的项目；',
	        	conditionscon8126:'<span>•</span>侵犯第三方知识产权的货物或者服务；',
	        	conditionscon8127:'<span>•</span>活动物；',
	        	conditionscon8128:'<span>•</span>烟花；',
	        	conditionscon8129:'<span>•</span>非法野生动物贸易；',
	        	conditionscon8130:'<span>•</span>武器（包括但不限于，刀具、枪支、枪支或弹药）；',
	        	conditionscon8131:'<span>•</span>复制品和/或无牌商标产品；',
	        	conditionscon8132:'<span>•</span>市场限制的任何其他类别',
	        	conditionscon8133:'<span>•</span>V-Stars决定禁止的任何其他类别或付款人，由其自行决定；',
	        	conditionscon82:'8.2 如果你在美国外国资产管理局限制的任何国家居住、工作或从事商业活动，你就不应该使用V-Stars服务。我们可以自行决定在任何时候停止或限制我们对其他国家居民的服务，而不必事先通知。',
	        	conditionscon83:'8.3 我们有权暂停或终止使用V-Stars服务（包括获取资金），如果我们合理地认为必须遵守法律或遵守有关政府当局或认可机构的建议金融犯罪。',
	        	conditionscon84:'8.4 严禁使用V-Stars服务，包括欺诈和洗钱等非法用途。我们将向相关执法机构报告任何可疑活动。禁止在任何企图滥用、剥削或规避任何法律或法规的情况下使用V-Stars服务。',
	        	conditionscon85:'8.5 如果您违反或违反本节所包含的禁令或未经V-Stars的必要批准进行任何交易，我们保留（i）反向交易的权利；（ii）终止或暂停使用V-Stars服务；（iii）报告交易。有关执法机构；（四）要求赔偿损失。 ',
	        	
	        	conditionscon911:'9.1 你同意以下陈述是真实和准确的，你承认我们可能拒绝处理你的交易，甚至终止我们的关系，如果我们发现在任何阶段，他们是不真实的和准确的：',
	        	conditionscon912:'<span>(i)</span> 你已经18岁了',
	        	conditionscon913:'<span>(ii)</span> 你被正式注册在你的公司或机构所在地，并合法存在。',
	        	conditionscon914:'<span>(iii)</span> 你有充分的权力进入本协议及其下的服务；',
	        	conditionscon915:'<span>(iv)</span> 你是被转移资金的受益所有人；',
	        	conditionscon916:'<span>(v)</span> 你不代表他人行事，除非你得到我们的授权和核实。',
	        	conditionscon917:'<span>(vi)</span> 你有一切必要的权力进入交易以及与V-Stars服务有关的交易；',
	        	conditionscon918:'<span>(vii)</span> 您已按照所有适用的法律和法规进行操作，您已获得所有必需的和有效的许可证、同意书、证书和批准书（无论是由政府或私人发行）用于经营您的企业，您不知道任何情况。许可证、同意书、证书、批准书可以吊销、注销或者不续签的；',
	        	conditionscon919:'<span>(viii)</span> 你使用V-Stars服务不会侵犯或误导任何第三方的知识产权。',
	        	
	        	conditionscon92:'9.2 您的V-Stars服务的使用将严格遵守这些条款和条件，以及所有适用的法律和法规（包括但不限于在您的国家、州、市或其他政府地区的任何地方性法律或法规），关于在线行为和可接受的CONT。ENT，并包括所有有关从美国或你所在国家出口的技术数据的法律适用； ',
	        	
	        	conditionscon101:'10.1 您可以随时通知我们书面终止本协议。',
	        	
	        	conditionscon1021:'10.2 我们可以随时给你一个月的书面通知，终止本协议。如果我们合理地相信，我们也可以立即终止或不另行通知：',
	        	conditionscon1022:'<span>•</span> 你已经认真或多次违反了本协议的条款，',
	        	conditionscon1023:'<span>•</span> 你提供虚假信息给我们，',
	        	conditionscon1024:'<span>•</span> 你所请求的服务与诈骗、洗钱、恐怖主义融资、逃税或其他犯罪活动有关，',
	        	conditionscon1025:'<span>•</span> 这意味着我们可能违反法律、法规、法规或其他义务，或可能使我们暴露第三方的索赔，',
	        	conditionscon1026:'<span>•</span> 你威胁或辱骂我们的工作人员，',
	        	conditionscon1027:'<span>•</span> 你破产或无力偿债，或出现破产事件。',
	        	
	        	conditionscon103:'10.3 任何抱怨我们或我们提供的服务，应立即联系我们的V-Stars客户支持或发电子邮件给我们complaints@vstarsfx.com。我们可以向您发送投诉或向您索取更多关于您投诉的信息。',
	        	conditionscon104:'10.4 我们的目标是在可能的情况下为您的投诉提供及时的答复或解决方案。然而，这里所包含的任何东西，都不是由V-Stars来解决你的抱怨的承诺。',
	        	conditionscon111:'11.1 对于因延误或失败而造成的任何损失或损害，V-Stars不应承担任何责任，该延迟或失败是由于我们无法控制的原因造成的，也不是由我们的过失或过失引起的，包括但不限于战争，I的威胁。战争、暴乱或其他不文明行为、暴动、上帝行为、政府或任何其他外国法律当局或其他任何工业或贸易争端、火灾、爆炸、暴风雨、洪水、雷电、地震、流行病、大流行等自然卡拉米所施加的限制。',
	        	conditionscon112:'11.2 在任何有关提供或提供的货物和服务的出版物和材料中，我们和/或任何其他第三方所提供的陈述、陈述或描述，我们不承担任何错误陈述、错误、默认、失败、遗漏和任何责任。由我们。此外，对提供V-Stars服务的第三方的行为和遗漏，我们不负任何责任。',
	        	conditionscon113:'11.3 除本协议明文规定外，本公司不放弃因V-Stars服务提供货物或服务而产生的所有索赔、责任和责任（包括其任何经济损失）。我们对货物和服务不作明示或默示的陈述或保证。在不限制上述情况的情况下，我们不保证货物和服务和所使用的设施将不间断地、不延误地、错误地和无缺陷的、不漏报的，或将满足任何特定的性能或质量标准。我们明确否认所有明示、默示或法定保证，包括但不限于保证适销性、所有权、针对特定目的的适用性、不侵权、兼容性、安全性准确性、及时性和完整性。在任何情况下，我们不应承担任何直接、间接、附带、特殊、示范、惩罚性、后果性或其他损害（包括但不限于使用损失、数据或利润的责任），无论发生什么原因，包括但不限于合同、过失。或与提供V-Stars服务有关的其他侵权行为。我们明确地排除了对所提供的货物和服务直接或间接遭受的任何损害或损害的一切责任。 ',
	        	conditionscon114:'11.4 在不损害前述情况的情况下，如果我们对V-Stars服务所产生的任何损失或损害承担责任，您可以从我们这里收回的最大金额不超过Y所支付的费用总额。在行动发生前十二个月（12个月）内发生。',
	        	conditionscon115:'11.5 就任何入站付款而言，你可以从市场上免除这类付款的责任，因为与之相关的资金是由V-Stars接收的，而不是以后的资金通过V-Stars结算给你的。根据本规定，每个市场应为第三方受益人。',
	        	conditionscon116:'11.6 您承认V-Stars将使用服务提供商提供V-Stars服务。在服务提供者和你自己之间没有商业协议，并且每个服务提供者都不会对你有直接责任。',
	        	conditionscon117:'11.7 V-Stars服务被提供“原样”。V-Stars及其服务提供商因此不承认任何类型的明示或默示的保证，包括但不限于适销性、适合特定目的和不侵权的保证。无论是V-Stars还是它的服务提供商，都不保证我们的服务将是无差错的或其访问将是连续的或不间断的。您知道您从我们的服务下载或以其他方式获得内容或服务通过您自己的自由裁量权和风险。',
	        	conditionscon118:'11.8 您同意赔偿和保护无害的V-Stars及其服务提供商及其相应的董事、官员、雇员和代理人，以避免和使用任何由您使用V-Stars服务而引起的任何和所有索赔和费用，包括律师费，包括但不限于您。这违反了V-Stars条款和条件。',
	        	conditionscon119:'11.9 本合同条款第10条应在本合同终止后继续存续。',
	        	conditionscon121:'12.1 如果这些条款和条件由法院、仲裁机构或有管辖权的机构确定为无效、非法或不可执行的，则应对该条款进行改革、修改和解释，使之有效、合法和可执行，并使其近似接近。该条款的原意，其余条款和条件完全保留和生效。 ',
	        	conditionscon122:'12.2 在行使这些条款和条件下，我们在行使任何权利、权力或补救措施时，没有任何失败或延误，应作为其放弃，也不应单独或部分行使同样的义务，不得进一步行使或行使任何其他权利、权力或救济。在不限制上述条件的情况下，我们对任何违反本条款的任何放弃都不应被视为是对本合同或本条款的任何其他违反的放弃。',
	        	conditionscon123:'12.3 任何管辖权的法律规定的这些条款和条件的违法性、无效性或不可执行性，不影响任何其他司法管辖区法律的合法性、有效性或可执行性，也不影响任何其他规定的合法性、有效性或可执行性。',
	        	conditionscon124:'12.4 未经我方书面同意，不得转让或转让本合同项下的任何权利和义务。',
	        	conditionscon1311:'13.1 在本条款中，下列术语具有以下含义：',
	        	conditionscon1312:'<span>“协议”</span>是指这些一般条款和条件，以及所有构成协议的附表和附件。',
	        	conditionscon1313:'<span>“营业日”</span>是指除星期六、星期日和公众假期外，香港商业银行一般可提供服务的任何一天。',
	        	conditionscon1314:'<span>“买方”</span>是指直接或在市场上购买产品的人或实体。',
	        	conditionscon1315:'<span>“客户”</span>是指与本协定项下的服务有关的条款，或与本协议有关的商业惯例，一个人的行为或委托行动，主要是为了与该人的贸易或业务有关的目的。 ',
	        	conditionscon1316:'<span>“客户银行账户”</span>是指您在香港或PRC的指定受益人银行账户，您希望通过使用V-Stars服务来接收通过我们结算的资金，而该银行账户应由您在V-Stars账户中指定。',
	        	conditionscon1317:'<span>“指定支付服务”</span>是指（i）美国支付服务；（ii）欧盟支付服务；（iii）其他入境支付服务。',
	        	conditionscon1318:'<span>“欧盟”</span>的意思是欧盟。',
	        	conditionscon1319:'<span>“欧盟支付服务”</span>是指通过单一欧洲支付区域（SEPA）系统提供的V-Stars服务中的欧元支付服务。',
	        	conditionscon13110:'<span>“欧元”</span>是指欧元，欧盟的法定货币。',
	        	conditionscon13111:'<span>“费用”</span>是指你支付给我们的使用V-Stars服务的费用。',
	        	conditionscon13112:'<span>“资金”</span>指在V-Stars服务过程中由V-Stars或其服务提供商为您所接收的资金。',
	        	conditionscon13113:'<span>“香港”</span>是指PRC的香港特别行政区。',
	        	conditionscon13114:'<span>“入站付款”</span>是指通过指定的支付服务由V-Stars接收的任何资金。',
	        	conditionscon13115:'<span>“市场”</span>或<span>“付款人”</span>指的是由V-Stars认可的电子商务市场，不时接受V-Stars服务，您是根据市场和市场的书面协议销售的产品。',
	        	conditionscon13116:'<span>“其他入境支付服务”</span>是指通过V-Stars指定的系统，时不时提供以V-STAR服务提供的欧元和美元以外的货币的支付服务。',
	        	conditionscon13117:'<span>“其他地点”</span>指的是美国和EU以外的其他地方，V-Stars不时提供其他入境支付服务。',
	        	conditionscon13118:'<span>“PRC”</span>是指中华人民共和国，出于这些使用条款的目的，它不包括香港、澳门特别行政区和台湾。',
	        	conditionscon13119:'<span>“产品”</span>指的是一种通过市场销售的产品，您希望使用V-Stars服务来接收付款。',
	        	conditionscon13120:'<span>“服务提供者”</span>是指第三方在提供V-Stars服务的过程中提供的设施，包括但不限于银行、支付服务提供商、清算网络和其他第三方支付处理服务提供商。',
	        	conditionscon13121:'<span>“T&Cs”</span> 意味着V-Stars术语和条件的本协定',
	        	conditionscon13122:'<span>“交易”</span>是指涉及V-Stars服务的实际或尝试支付交易。',
	        	conditionscon13123:'<span>“V-Stars帐户”</span>指的是一个独特的帐户内的V-Stars服务，为您注册，并能够持续使用的V-Stars服务。为避免存疑，该帐户不构成银行帐户。您希望提供您的信息、市场商店信息、交易历史和与您使用V-Stars服务有关的其他信息。',
	        	conditionscon13124:'<span>“V-Stars银行账户”</span>是指在美国或欧盟的金融机构或其他地方保留的V-Stars的经营账户，在此基础上，您可以通过V-Stars作为您的代理来接收资金。V-Stars将通知你的V-Stars服务证书一旦你被批准使用的V-Stars服务。',
	        	conditionscon13125:'<span>“美国”</span>是指美利坚合众国。',
	        	conditionscon13126:'<span>“美元”</span>是指美元，美国的法定货币。',
	        	conditionscon13127:'<span>“美国支付服务”</span>是指通过美国自动结算所（Ach）提供的V-STAR服务提供的美元支付服务。',
	        	
	        	credits:'图片赞助',
	        	creditscon1:'我们十分感激以下设计师的分享。',
	        	creditscon2:'照片',
	        	creditscon3:'<a href="https://unsplash.com/photos/WMSvsWzhM0g?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Ruslan Bardash</a>在<a href="https://unsplash.com/search/photos/hong-kong?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>提供的照片',
	        	creditscon7:'<a href="https://unsplash.com/photos/Oja2ty_9ZLM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Benjamin Davies</a> 在 <a href="https://unsplash.com/@bendavisual?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>提供的照片',
	        	creditscon4:'<a href="https://www.pexels.com/">Pexels</a>提供的照片',
	        	serviceotherpagesquestion:'帮助',
	        	serviceotherpagescredits:'摄影鸣谢',
	        	serviceotherpagescreditstc:'条款规定',
	        	creditscon5:'图标',
	       		creditscon6:'图标 <a href="http://www.freepik.com" title="Freepik">Freepik</a> 来自 <a href="https://www.flaticon.com/"title="Flaticon">www.flaticon.com</a> 授权自<a href="http://creativecommons.org/licenses/by/3.0/" title="CreativeCommons BY 3.0" target="_blank">CC 3.0 BY</a>',
	       }
	    }
	})
	if(localStorage.getItem("language")){
		if(localStorage.getItem("language")=="ch"){
			di18n.setLocale('ch');
		}else{
			di18n.setLocale('en');
		}
	}else{
		localStorage.setItem('language', "en");
		di18n.setLocale('en');
	}
	$("#language>div").click(function(){
		
		if($(this).children("img").attr("src")=='images/en.png'){
			di18n.setLocale('en');
		}else{
			di18n.setLocale('ch');
		}
	})
	